# Water
block.10004=minecraft:water minecraft:flowing_water

# SSS weak & no waving
block.10005=minecraft:cobweb minecraft:bamboo  minecraft:slime_block minecraft:honey_block %minecraft:wool minecraft:hay_block minecraft:packed_ice

# SSS strong
block.10006=minecraft:dead_bush minecraft:sugar_cane minecraft:sweet_berry_bush minecraft:seagrass minecraft:tall_seagrass minecraft:kelp minecraft:kelp_plant minecraft:short_dry_grass minecraft:tall_dry_grass minecraft:cactus_flower minecraft:ice

# Tall plants (lower half)
block.10007=minecraft:large_fern:half=lower minecraft:tall_grass:half=lower minecraft:peony:half=lower minecraft:rose_bush:half=lower minecraft:lilac:half=lower minecraft:sunflower:half=lower minecraft:pitcher_plant:half=lower

# Tall plants (upper half)
block.10008=minecraft:large_fern:half=upper minecraft:tall_grass:half=upper minecraft:peony:half=upper minecraft:rose_bush:half=upper minecraft:lilac:half=upper minecraft:sunflower:half=upper minecraft:pitcher_plant:half=upper

# Short plants
block.10009=minecraft:short_grass %minecraft:saplings minecraft:grass minecraft:fern %minecraft:small_flowers minecraft:brown_mushroom minecraft:red_mushroom minecraft:bush minecraft:firefly_bush minecraft:wheat minecraft:potatoes minecraft:carrots minecraft:beetroots

# Leaves
block.10010=%minecraft:leaves minecraft:vine

# Solid blocks that should less floodfill passthough
block.10020=%minecraft:fences %minecraft:slabs %minecraft:walls %minecraft:doors %minecraft:trapdoors %minecraft:pressure_plates %minecraft:buttons %minecraft:fence_gates %minecraft:bars %minecraft:chains %minecraft:carpets %minecraft:beds minecraft:big_dripleaf minecraft:chorus_plant minecraft:sculk_shrieker minecraft:stonecutter %minecraft:anvil minecraft:bell minecraft:scaffolding %minecraft:lightning_rods %minecraft:flower_pots %minecraft:wooden_shelves minecraft:lever minecraft:tripwire_hook minecraft:daylight_sensor minecraft:hopper 

# Light emitting blocks
# Red
block.10021=minecraft:redstone_torch minecraft:redstone_wall_torch %minecraft:redstone_ores

# Orange
block.10022=minecraft:wall_torch minecraft:jack_o_lantern minecraft:fire minecraft:cave_vines minecraft:cave_vines_plant minecraft:lava minecraft:campfire minecraft:magma_block minecraft:ochre_froglight minecraft:torch minecraft:lantern

# Yellow
block.10023=minecraft:redstone_lamp minecraft:glowstone

# Lime
block.10024=minecraft:copper_torch minecraft:copper_wall_torch minecraft:verdant_froglight minecraft:sea_pickle minecraft:end_portal

# Turqoise
block.10025=minecraft:sea_lantern minecraft:sculk_sensor minecraft:beacon minecraft:enchanting_table minecraft:glow_lichen 

# Blue
block.10026=minecraft:soul_torch minecraft:soul_wall_torch minecraft:soul_campfire minecraft:soul_lantern

# Purple
block.10027=minecraft:calibrated_sculk_sensor minecraft:medium_amethyst_bud minecraft:large_amethyst_bud minecraft:amethyst_cluster minecraft:pearlescent_froglight
