sliders=SHADOW_BIAS SHADOW_DISTORT_FACTOR SHADOW_BRIGHTNESS shadowMapResolution SHARPENING_AMOUNT

particles.ordering=mixed
separateAo=true
clouds=off
stars=false


iris.features.optional=REVERSED_CULLING BLOCK_EMISSION_ATTRIBUTE FADE_VARIABLE
iris.features.required=SSBO CUSTOM_IMAGES SEPARATE_HARDWARE_SAMPLERS HIGHER_SHADOWCOLOR

#if MC_VERSION < 12105
separateEntityDraws=true
#endif

#ifdef VOXELISATION
shadow.culling=reversed
voxelizeLightBlocks=true
#if VOXEL_DISTANCE == 64
image.voxelImg_a=voxelImgSampler_a RGBA RGBA16 UNSIGNED_SHORT false false 128 64 128
image.voxelImg_b=voxelImgSampler_b RGBA RGBA16 UNSIGNED_SHORT false false 128 64 128
#elif VOXEL_DISTANCE == 96
image.voxelImg_a=voxelImgSampler_a RGBA RGBA16 UNSIGNED_SHORT false false 192 96 192
image.voxelImg_b=voxelImgSampler_b RGBA RGBA16 UNSIGNED_SHORT false false 192 96 192
#elif VOXEL_DISTANCE == 128
image.voxelImg_a=voxelImgSampler_a RGBA RGBA16 UNSIGNED_SHORT false false 256 128 256
image.voxelImg_b=voxelImgSampler_b RGBA RGBA16 UNSIGNED_SHORT false false 256 128 256
#elif VOXEL_DISTANCE == 192
image.voxelImg_a=voxelImgSampler_a RGBA RGBA16 UNSIGNED_SHORT false false 384 192 384
image.voxelImg_b=voxelImgSampler_b RGBA RGBA16 UNSIGNED_SHORT false false 384 192 384
#elif VOXEL_DISTANCE == 256
image.voxelImg_b=voxelImgSampler_b RGBA RGBA16 UNSIGNED_SHORT false false 512 128 512
image.voxelImg_a=voxelImgSampler_a RGBA RGBA16 UNSIGNED_SHORT false false 512 128 512
#endif
#endif

profile.TOASTER=AA_MODE=0 shadowMapResolution=1024 shadowDistance=96.0 SHADOW_FILTER=1 VL_OVERWORLD_MODE=0 VL_WATER_MODE=0 VL_SAMPLES=8 AO_MODE=0 !RSM
profile.LOW=AA_MODE=1 shadowMapResolution=1024 shadowDistance=128.0 SHADOW_FILTER=1 VL_OVERWORLD_MODE=1 VL_WATER_MODE=0 VL_SAMPLES=8 AO_MODE=1 !RSM
profile.MEDIUM=AA_MODE=1 shadowMapResolution=2048 shadowDistance=192.0 SHADOW_FILTER=2 VL_OVERWORLD_MODE=1 VL_WATER_MODE=0 VL_SAMPLES=12 AO_MODE=2 !RSM
profile.HIGH=AA_MODE=1 shadowMapResolution=2048 shadowDistance=192.0 SHADOW_FILTER=2 VL_OVERWORLD_MODE=1 VL_WATER_MODE=1 VL_SAMPLES=12 AO_MODE=2 RSM
profile.ULTRA=AA_MODE=1 shadowMapResolution=3072 shadowDistance=256.0 SHADOW_FILTER=2 VL_OVERWORLD_MODE=1 VL_WATER_MODE=1 VL_SAMPLES=16 AO_MODE=2 RSM

screen=<profile> INFO SCREENSHOT_MODE <empty> <empty> <empty> [screen_LIGHTING] [screen_SKY] [screen_FOG] [screen_MATERIALS] [screen_CAMERA_EFFECTS] [screen_POST_PROCESSING] [screen_COLORS] [screen_WEATHER] [screen_VOXELISATION]
screen.screen_LIGHTING=[screen_SHADOWS] [screen_INDIRECT_LIGHTING]
screen.screen_SHADOWS=shadowMapResolution shadowDistance SHADOW_FILTER SHADOW_FILTER_SIZE SCREENSPACE_SHADOWS_FALLBACK
screen.screen_INDIRECT_LIGHTING=AO_MODE RSM GTAO_SAMPLES RSM_SAMPLE_COUNT
screen.screen_FOG=VL_OVERWORLD_MODE VL_OVERWORLD_STRENGTH VL_WATER_MODE <empty> VL_SAMPLES <empty> <empty> <empty> BORDER_FOG
screen.screen_MATERIALS=[screen_REFLECTIONS] <empty> PBR_NORMAL PBR_EMISSIVENESS PBR_SSS [screen_POM] <empty> SSS_STRENGTH_WEAK SSS_STRENGTH_STRONG
screen.screen_MATERIALS.columns=1
screen.screen_REFLECTIONS=SSR_STEPS REFLECTION_CAPTURE <empty> PBR_SPECULAR ROUGH_REFLECTIONS
screen.screen_REFLECTIONS.columns=1
screen.screen_POM=PBR_POM POM_MAX_DEPTH POM_STEP_COUNT
screen.screen_POST_PROCESSING=AA_MODE <empty> <empty> <empty> TONEMAP_OPERATOR SATURATION VIBRANCE CONTRAST PURKINJE_EFFECT_STRENGTH <empty> <empty> <empty> [screen_CHANNEL_MIXER] [screen_COLOR_BALANCING]
screen.screen_CHANNEL_MIXER=CHANNEL_MIXER <empty> <empty> CM_R_IN_R CM_G_IN_R CM_B_IN_R CM_R_IN_G CM_G_IN_G CM_B_IN_G CM_R_IN_B CM_G_IN_B CM_B_IN_B
screen.screen_CHANNEL_MIXER.columns=3
screen.screen_COLOR_BALANCING=COLOR_BALANCING <empty> <empty> SHADOWS_CYAN_TO_RED SHADOWS_MAGENTA_TO_GREEN SHADOWS_YELLOW_TO_BLUE MIDS_CYAN_TO_RED MIDS_MAGENTA_TO_GREEN MIDS_YELLOW_TO_BLUE HIGHS_CYAN_TO_RED HIGHS_MAGENTA_TO_GREEN HIGHS_YELLOW_TO_BLUE
screen.screen_COLOR_BALANCING.columns=3
screen.screen_CAMERA_EFFECTS=VIGNETTE VIGNETTE_FALLOFF BLOOM BLOOM_STRENGTH LENS_FLARE LENS_FLARE_STRENGTH DOF [screen_DOF_SETTINGS] <empty> <empty> [screen_CAMERA_DEGRADATION] <empty> <empty> <empty> EXPOSURE_MULT EXPOSURE_SPEED
screen.screen_CAMERA_EFFECTS.columns=2
screen.screen_DOF_SETTINGS=DOF_APERTURE_SIZE DOF_FOCUS_ADJUSTMENT_SPEED DOF_MANUAL_FOCUS DOF_FOCUS_DISTANCE DOF_SHOW_FOCUS
screen.screen_CAMERA_DEGRADATION=FILM_GRAIN FILM_GRAIN_STRENGTH FILM_GRAIN_SIZE FILM_GRAIN_MAX_BRIGHTNESS <empty> <empty> CHROMATIC_ABERRATION CA_STRENGTH PIXELATION PIXELATION_AMOUNT
screen.screen_COLORS=[screen_OVERWORLD] [screen_NETHER] [screen_END] [screen_OTHER]
screen.screen_OVERWORLD=c_SUN_R c_SUN_G c_SUN_B c_MOON_R c_MOON_G c_MOON_B c_DAY_AMBIENT_R c_DAY_AMBIENT_G c_DAY_AMBIENT_B c_NIGHT_AMBIENT_R c_NIGHT_AMBIENT_G c_NIGHT_AMBIENT_B
screen.screen_OVERWORLD.columns=3
screen.screen_NETHER=UNDER_CONSTRUCTION
screen.screen_END=UNDER_CONSTRUCTION
screen.screen_OTHER=c_WATER_SCATTERING_R c_WATER_SCATTERING_G c_WATER_SCATTERING_B c_WATER_ABSORBTION_R c_WATER_ABSORBTION_G c_WATER_ABSORBTION_B c_PURKINJE_R c_PURKINJE_G c_PURKINJE_B c_MIN_LIGHT
screen.screen_OTHER.columns=3
screen.screen_WEATHER=[screen_WIND] [screen_SEASONAL_COLORS] [screen_ATMOSPHERE_PARAMS]
screen.screen_SEASONAL_COLORS=SEASONAL_COLORS SEASONS_TEMPERATE_BIOME_CHECK <empty> SPRING_HUE SPRING_SAT SPRING_VAL SUMMER_HUE SUMMER_SAT SUMMER_VAL AUTUMN_HUE AUTUMN_SAT AUTUMN_VAL WINTER_HUE WINTER_SAT WINTER_VAL
screen.screen_ATMOSPHERE_PARAMS=SCREENSHOT_MODE INFO_PARAMS <empty> <empty>
screen.screen_SEASONAL_COLORS.columns=3
screen.screen_WIND=WAVY_PLANTS WAVE_AMPLITUDE WAVE_SPEED WAVE_SIZE WAVE_LEAVES
screen.screen_SKY=CLOUDS VOLUMETRICS_RES AURORA
screen.screen_VOXELISATION=VOXELISATION VOXEL_DISTANCE <empty> <empty> COLORED_LIGHTS

sliders=FILM_GRAIN_SIZE FILM_GRAIN_MAX_BRIGHTNESS VOXEL_DISTANCE VL_OVERWORLD_STRENGTH GTAO_SAMPLES RSM_SAMPLE_COUNT VL_SAMPLES shadowMapResolution shadowDistance SSS_STRENGTH_WEAK SSS_STRENGTH_STRONG SHADOW_FILTER_SIZE VIGNETTE_FALLOFF BLOOM_STRENGTH FILM_GRAIN_STRENGTH EXPOSURE_MULT EXPOSURE_SPEED LENS_FLARE_STRENGTH VIBRANCE SATURATION CONTRAST PURKINJE_EFFECT_STRENGTH WAVE_AMPLITUDE WAVE_SPEED WAVE_SIZE POM_MAX_DEPTH POM_STEP_COUNT CA_STRENGTH DOF_APERTURE_SIZE DOF_FOCUS_ADJUSTMENT_SPEED DOF_FOCUS_DISTANCE CM_R_IN_R CM_G_IN_R CM_B_IN_R CM_R_IN_G CM_G_IN_G CM_B_IN_G CM_R_IN_B CM_G_IN_B CM_B_IN_B SHADOWS_CYAN_TO_RED SHADOWS_MAGENTA_TO_GREEN SHADOWS_YELLOW_TO_BLUE MIDS_CYAN_TO_RED MIDS_MAGENTA_TO_GREEN MIDS_YELLOW_TO_BLUE HIGHS_CYAN_TO_RED HIGHS_MAGENTA_TO_GREEN HIGHS_YELLOW_TO_BLUE c_SUN_R c_SUN_G c_SUN_B c_MOON_R c_MOON_G c_MOON_B c_DAY_AMBIENT_R c_DAY_AMBIENT_G c_DAY_AMBIENT_B c_NIGHT_AMBIENT_R c_NIGHT_AMBIENT_G c_NIGHT_AMBIENT_B c_WATER_SCATTERING_R c_WATER_SCATTERING_G c_WATER_SCATTERING_B c_WATER_ABSORBTION_R c_WATER_ABSORBTION_G c_WATER_ABSORBTION_B c_PURKINJE_R c_PURKINJE_G c_PURKINJE_B c_MIN_LIGHT VOLUMETRICS_RES SSR_STEPS SPRING_HUE SPRING_SAT SPRING_VAL SUMMER_HUE SUMMER_SAT SUMMER_VAL AUTUMN_HUE AUTUMN_SAT AUTUMN_VAL WINTER_HUE WINTER_SAT WINTER_VAL PIXELATION_AMOUNT

bufferObject.0=112
bufferObject.1=1024
customTexture.waterNoise=/lib/img/water.png
customTexture.cloudNoise=/lib/img/cloud_noise.png
customTexture.blueNoiseTexture=/lib/img/blue_noise.png
customTexture.smaaAreaTexture=/lib/img/smaaArea.png
customTexture.smaaSearchTexture=/lib/img/smaaSearch.png
customTexture.worleyNoiseTexture=/lib/img/worley_perlin.bin TEXTURE_3D R8 64 64 64 RED UNSIGNED_BYTE
customTexture.windTexture=/lib/img/worley_noise+normals.png
customTexture.milkyWay=/lib/img/milky_way.png

uniform.vec2.resolution=vec2(viewWidth, viewHeight)
uniform.vec2.resolutionInv=vec2(1.0/viewWidth, 1.0/viewHeight)

variable.float.gr=1.32471795724474602596

#if AA_MODE == 1
uniform.vec2.taaJitter=if(frameCounter%2 == 0, vec2(0.25 / viewWidth, -0.25 / viewHeight), vec2(-0.25 / viewWidth, 0.25 / viewHeight))
#elif AA_MODE == 2
variable.float.jitterX=frac(0.5 + frameCounter / gr) * 2 - 1
variable.float.jitterY=frac(0.5 + frameCounter / (gr*gr)) * 2 - 1
uniform.vec2.taaJitter=vec2(jitterX/viewWidth, jitterY/viewHeight)
#else
uniform.vec2.taaJitter=vec2(0, 0)
#endif

variable.float.sunL=1/sqrt(sunPosition.x*sunPosition.x+sunPosition.y*sunPosition.y+sunPosition.z*sunPosition.z)
uniform.vec3.sunPosN=vec3(sunPosition.x*sunL, sunPosition.y*sunL, sunPosition.z*sunL)
variable.float.slpL=1/sqrt(shadowLightPosition.x*shadowLightPosition.x+shadowLightPosition.y*shadowLightPosition.y+shadowLightPosition.z*shadowLightPosition.z)
uniform.vec3.sLightPosN=vec3(shadowLightPosition.x*slpL, shadowLightPosition.y*slpL, shadowLightPosition.z*slpL)

uniform.float.isOutdoorsSmooth=smooth(if(eyeBrightness.y > 50, 1, 0), 15, 6)

uniform.float.precipitationSmooth=smooth(biome_precipitation, 150, 150)

# Randomize the clouds every time the shader is reloaded
#ifdef SCREENSHOT_MODE
variable.float.randomFloat=0.5
#else
variable.float.randomFloat=smooth(random(), 2147483647, 2147483647)
#endif
variable.float.randomA=frac(randomFloat * 20 + 1.61803398875)
variable.float.randomB=frac(randomFloat * 60 + 1.61803398875 * 2)

# 0 - Spring, 3 - Winter
variable.float.worldDayMod=worldDay%120
variable.int.season=floor(worldDayMod / 30.0)
variable.float.seasonHumidity=if(season == 0, 1, if(season == 1, 0, if(season == 2, 3, -2)))
variable.float.humidity=smooth(seasonHumidity * 0.5 + rainfall * rainfall * 1.5, 30, 30)

uniform.float.cloudStartOffset=(randomB * 2 - 1) * 10000
uniform.float.cloudCoverageVl=max(1, 4 + 4 * randomFloat - 4 * rainStrength - 2 * thunderStrength - humidity * 0.7)
uniform.float.cloudCoverageFlat=4 + 6 * (randomA)

uniform.float.fogAmount=max(0, (1 - randomA) + rainStrength * 3 + thunderStrength * 3 + humidity - 1)
uniform.float.anisotropy=0.75 + 0.15 * randomB - 0.25 * rainStrength - 0.1 * thunderStrength

uniform.float.betaRfact=0.8 + randomB * 0.4

variable.float.randBSigned=randomB * 2 - 1
uniform.vec2.windDirection=vec2(randBSigned, sqrt(1 - randBSigned * randBSigned))

image.image0=image0Sampler RGBA RGBA16F HALF_FLOAT true true 1.0 1.0
image.image1=image1Sampler RG RG8 UNSIGNED_BYTE false true 1.0 1.0
image.image2=image2Sampler RGBA RGBA16F HALF_FLOAT false true 1.0 1.0
image.atm_transmittance=atm_transmittance_sampler RGBA RGBA8 UNSIGNED_BYTE false false 256 64
image.atm_skyview=atm_skyview_sampler RGBA RGBA8 UNSIGNED_BYTE false false 128 64
image.atm_multi_scattering=atm_multi_scattering_sampler RGBA RGBA16F HALF_FLOAT false false 32 32

program.world0/composite8.enabled=BLOOM
program.world0/composite9.enabled=BLOOM
program.world0/composite10.enabled=BLOOM
program.world0/composite11.enabled=BLOOM
program.world0/composite12.enabled=BLOOM
program.world0/composite13.enabled=BLOOM
program.world0/composite14.enabled=BLOOM
program.world0/composite15.enabled=BLOOM
program.world0/composite16.enabled=BLOOM
program.world0/composite17.enabled=BLOOM
program.world0/composite18.enabled=BLOOM
program.world0/composite19.enabled=BLOOM

program.world0/begin.enabled=VOXELISATION && COLORED_LIGHTS
program.world1/begin.enabled=VOXELISATION && COLORED_LIGHTS
program.world-1/begin.enabled=VOXELISATION && COLORED_LIGHTS


#if AA_MODE == 1
program.world0/composite48.enabled=true
program.world1/composite48.enabled=true
program.world-1/composite48.enabled=true
#else
program.world0/composite48.enabled=false
program.world1/composite48.enabled=false
program.world-1/composite48.enabled=false
#endif

program.world0/composite51.enabled=DOF
program.world-1/composite51.enabled=DOF
program.world1/composite51.enabled=DOF

program.world0/composite1.enabled=CLOUDS
program.world-1/composite1.enabled=false
program.world1/composite1.enabled=false

program.world0/composite.enabled=REFLECTION_CAPTURE
program.world-1/composite.enabled=REFLECTION_CAPTURE
program.world1/composite.enabled=REFLECTION_CAPTURE

program.world0/deferred.enabled=SPATIAL_DENOISING
program.world-1/deferred.enabled=SPATIAL_DENOISING
program.world1/deferred.enabled=SPATIAL_DENOISING
program.world0/deferred1.enabled=SPATIAL_DENOISING
program.world-1/deferred1.enabled=SPATIAL_DENOISING
program.world1/deferred1.enabled=SPATIAL_DENOISING

program.world0/composite52.enabled=PIXELATION
program.world-1/composite52.enabled=PIXELATION
program.world1/composite52.enabled=PIXELATION

alphaTest.gbuffers_terrain = off
alphaTest.gbuffers_entities = off
alphaTest.gbuffers_hand = off
alphaTest.gbuffers_spidereyes = off
alphaTest.gbuffers_water = off
alphaTest.gbuffers_hand_water = off
alphaTest.gbuffers_basic = off
alphaTest.gbuffers_textured = off
alphaTest.shadow = off
alphaTest.shadowcomp = off
alphaTest.gbuffers_skybasic = off
alphaTest.gbuffers_weather = off

blend.gbuffers_terrain = off
blend.gbuffers_entities = off
blend.gbuffers_hand = off
blend.gbuffers_spidereyes = off
blend.gbuffers_basic = off
blend.shadow = off
blend.gbuffers_skybasic = off
blend.gbuffers_armor_glint = off
blend.gbuffers_water = off
blend.gbuffers_hand_water = off
blend.gbuffers_textured = off
blend.gbuffers_entities_translucent = off
blend.gbuffers_particles_translucent = off
blend.gbuffers_entities_translucent = off
blend.gbuffers_block_translucent = off
#if MC_VERSION < 12601
blend.gbuffers_damagedblock = off
#endif
blend.gbuffers_weather = ONE ONE ONE ONE
blend.dh_water = off
blend.gbuffers_water.colortex0 = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_hand_water.colortex0 = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_textured.colortex0 = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_particles_translucent.colortex0 = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_entities_translucent.colortex0 = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.gbuffers_block_translucent.colortex0 = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA
blend.dh_water.colortex0 = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA

# Additive blending for bloom
blend.composite13=ONE ONE ONE ONE
blend.composite14=ONE ONE ONE ONE
blend.composite15=ONE ONE ONE ONE
blend.composite16=ONE ONE ONE ONE

flip.deferred2.colortex10=true