item.100 = minecraft:soul_lantern minecraft:soul_campfire minecraft:soul_torch minecraft:beacon minecraft:sea_lantern
item.101 = minecraft:lantern minecraft:torch minecraft:glowstone minecraft:campfire minecraft:lava_bucket
item.102 = minecraft:redstone_block minecraft:redstone_torch minecraft:redstone
item.103 = minecraft:nether_star
item.104 = minecraft:end_rod