#version 430 core
// Generated by irisbridge from a shaderpack source. Do not edit.
#define MC_VERSION 12100
#define MC_GL_VERSION 460
#define MC_GLSL_VERSION 460
#define MC_MIPMAP_LEVEL 4
#define MC_RENDER_QUALITY 1.0
#define MC_SHADOW_QUALITY 1.0
#define MC_HAND_DEPTH 0.125
#define MC_NORMAL_MAP
#define MC_SPECULAR_MAP
#define MAX_COLOR_BUFFERS 16
#define IS_IRIS
#define IRIS_TAG_SUPPORT 2
#define IRIS_VERSION 10800
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUNSET 2
#define MC_RENDER_STAGE_CUSTOM_SKY 3
#define MC_RENDER_STAGE_SUN 4
#define MC_RENDER_STAGE_MOON 5
#define MC_RENDER_STAGE_STARS 6
#define MC_RENDER_STAGE_VOID 7
#define MC_RENDER_STAGE_TERRAIN_SOLID 8
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 9
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 10
#define MC_RENDER_STAGE_ENTITIES 11
#define MC_RENDER_STAGE_BLOCK_ENTITIES 12
#define MC_RENDER_STAGE_DESTROY 13
#define MC_RENDER_STAGE_OUTLINE 14
#define MC_RENDER_STAGE_DEBUG 15
#define MC_RENDER_STAGE_HAND_SOLID 16
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 17
#define MC_RENDER_STAGE_TRIPWIRE 18
#define MC_RENDER_STAGE_PARTICLES 19
#define MC_RENDER_STAGE_CLOUDS 20
#define MC_RENDER_STAGE_RAIN_SNOW 21
#define MC_RENDER_STAGE_WORLD_BORDER 22
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 23
#define MC_OS_LINUX
#define MC_GL_VENDOR_INTEL
#define MC_GL_RENDERER_INTEL

// ---- Cubyz compatibility shim ----
uniform mat4 cubyz_ModelViewMatrix;

// ---- shaderpack source ----
#define COMPUTE_SHADER
#ifndef COLOUR_COMMON_GLSL
#define COLOUR_COMMON_GLSL

#ifndef COLOUR_LIGHTS_GLSL
#define COLOUR_LIGHTS_GLSL

struct ColouredLight {
    uint blockID;
    float blockLightLevel;
    vec3 lightColour;
    bool natural;
};

const ColouredLight[] colouredLights = ColouredLight[47](
    ColouredLight(89, 15, vec3(1.0, 0.43, 0.0), true),     // [0] Glowstone (Confirmado)
ColouredLight(91, 15, vec3(1.0, 0.54, 0.0), true),     // [1] Jack o lantern
                                                         ColouredLight(138, 15, vec3(1.0, 1.0, 1.0), true),    // [2] Beacon
                                                         ColouredLight(169, 15, vec3(0.0, 0.5, 1.0), true),    // [3] Sea lantern
                                                         ColouredLight(213, 3, vec3(1.0, 0.3, 0.0), true),     // [4] Magma block

                                                         // Concretos Coloridos
                                                         ColouredLight(251, 10, vec3(1.0, 0.35, 0.0), false),   // [5] Orange concrete (Corrigido para ID base 251)
ColouredLight(253, 10, vec3(0.0, 0.3, 0.8), false),    // [6] Light blue concrete
                                                         ColouredLight(254, 10, vec3(1.0, 1.0, 0.0), false),    // [7] Yellow concrete
                                                         ColouredLight(255, 10, vec3(0.0, 0.8, 0.0), false),    // [8] Lime concrete
                                                         ColouredLight(260, 10, vec3(0.6, 0.0, 0.6), false),    // [9] Purple concrete
                                                         ColouredLight(264, 10, vec3(1.0, 0.0, 0.0), false),    // [10] Red concrete

                                                         // Iluminação Geral
                                                         ColouredLight(463, 15, vec3(1.0, 0.54, 0.0), true),    // [11] Lantern
                                                         ColouredLight(464, 15, vec3(1.0, 0.52, 0.0), true),    // [12] Campfire
                                                         ColouredLight(485, 15, vec3(1.0, 0.33, 0.0), true),    // [13] Shroomlight
                                                         ColouredLight(544, 10, vec3(0.5, 0.0, 1.0), true),    // [14] Crying obsidian

                                                         // Froglights (Corrigidos os IDs para sequência padrão)
                                                         ColouredLight(724, 15, vec3(0.9, 0.6, 0.9), true),    // [15] Pearlescent froglight
                                                         ColouredLight(725, 15, vec3(0.6, 0.9, 0.6), true),    // [16] Verdant froglight
                                                         ColouredLight(726, 15, vec3(0.9, 0.8, 0.5), true),    // [17] Ochre froglight

                                                         // Elementos das Almas (Soul) e Redstone
                                                         ColouredLight(465, 10, vec3(0.3, 0.7, 0.9), true),     // [18] Soul lantern
                                                         ColouredLight(466, 10, vec3(0.3, 0.7, 0.9), true),     // [19] Soul torch / Soul fire
                                                         ColouredLight(467, 7, vec3(1.0, 0.0, 0.0), true),      // [20] Redstone torch
                                                         ColouredLight(468, 13, vec3(0.91, 0.46, 0.11), true),   // [21] Furnace
                                                         ColouredLight(469, 14, vec3(0.9, 0.9, 1.0), true),     // [22] End rod
                                                         ColouredLight(470, 15, vec3(1.0, 0.4, 0.0), true),     // [23] Lava
                                                         ColouredLight(471, 15, vec3(1.0, 0.5, 0.0), true),     // [24] Fire
                                                         ColouredLight(472, 14, vec3(0.87, 0.75, 0.27), true),   // [25] Cave vines
                                                         ColouredLight(473, 15, vec3(0.3, 0.8, 0.8), true),     // [26] Conduit
                                                         ColouredLight(474, 13, vec3(0.6, 0.1, 0.8), true),     // [27] Respawn anchor
                                                         ColouredLight(475, 10, vec3(0.0, 0.4, 0.5), true),     // [28] Sculk catalyst
                                                         ColouredLight(480, 6, vec3(1.0, 0.0, 0.0), false),     // [29] Redstone block

                                                         // Blocos de Cobre (Copper Bulbs / Torches - Corrigidos para a faixa estável)
                                                         ColouredLight(491, 14, vec3(0.15, 0.93, 0.65), true),   // [30] Copper torch
                                                         ColouredLight(492, 15, vec3(0.12, 0.95, 0.60), true),   // [31] Copper lantern
                                                         ColouredLight(493, 15, vec3(0.96, 0.55, 0.25), true),   // [32] Copper bulb
                                                         ColouredLight(494, 12, vec3(0.87, 0.75, 0.27), true),   // [33] Firefly bush

                                                         // Categorias Globais (IDs altos mapeados por aproximação de tags)
                                                         ColouredLight(15008, 10, vec3(0.36, 0.78, 0.89), true), // Soul lantern (cat)
ColouredLight(15408, 10, vec3(0.36, 0.78, 0.89), true), // Soul fire (cat)
ColouredLight(15001, 7, vec3(0.88, 0.23, 0.23), true),  // Redstone torch (cat)
ColouredLight(15014, 13, vec3(0.91, 0.46, 0.11), true), // Furnace (cat)
ColouredLight(15003, 15, vec3(1.0, 0.43, 0.0), true),   // Glowstone (cat)
ColouredLight(15002, 15, vec3(1.0, 0.54, 0.0), true),   // Torch/Lantern/Campfire (cat)
ColouredLight(15007, 15, vec3(0.0, 0.0, 1.0), true),    // Sea lantern (cat)
ColouredLight(15005, 15, vec3(0.0, 1.0, 0.0), true),    // Verdant froglight (cat)
ColouredLight(15009, 15, vec3(1.0, 0.0, 1.0), true),    // Pearlescent froglight (cat)
ColouredLight(15025, 14, vec3(1.0, 1.0, 1.0), true),    // End rod/Beacon (cat)
ColouredLight(15302, 15, vec3(0.95, 0.47, 0.10), true), // Lava (cat)
ColouredLight(15402, 15, vec3(0.95, 0.47, 0.10), true), // Fire (cat)
ColouredLight(15709, 14, vec3(0.87, 0.75, 0.27), true)  // Cave vines (cat)
);

#endif

// ============================================
// DECLARAÇÕES DE UNIFORMS (precisa vir antes do blocklight_shadow.glsl)
// ============================================
#ifndef COMPUTE_SHADER
uniform mat4 gbufferModelView;
uniform mat4 gbufferModelViewInverse;
uniform mat4 gbufferProjection;
uniform mat4 gbufferProjectionInverse;
uniform vec3 cameraPosition;
uniform sampler2D depthtex0;
#endif

// ============================================
// INCLUI O SISTEMA DE SOMBRAS PARA LUZES DE BLOCO
// ============================================
// ============================================
// blocklight_shadow.glsl - Sombras para luzes de bloco
// ============================================

#ifndef BLOCKLIGHT_SHADOW_GLSL
#define BLOCKLIGHT_SHADOW_GLSL

// ============================================
// CONFIGURAÇÕES
// ============================================
#define MAX_BLOCKLIGHTS 64

// ============================================
// ESTRUTURA PARA LUZES DE BLOCO
// ============================================
struct BlockLight {
    vec3 position;
    float radius;
    vec3 color;
    float intensity;
};

// ============================================
// BUFFER DE LUZES (binding 3)
// ============================================
layout(std430, binding = 19) coherent buffer blockLightsBuffer {
    uint lightCount;
    BlockLight lights[MAX_BLOCKLIGHTS];
} blockLights;

// ============================================
// FUNÇÃO PARA REGISTRAR LUZ
// ============================================
void registerBlockLight(vec3 position, float radius, vec3 color, float intensity) {
    uint index = atomicAdd(blockLights.lightCount, 1u);
    if (index < MAX_BLOCKLIGHTS) {
        blockLights.lights[index].position = position;
        blockLights.lights[index].radius = radius;
        blockLights.lights[index].color = color;
        blockLights.lights[index].intensity = intensity;
    }
}

// ============================================
// FUNÇÕES DE SOMBRA (apenas para fragment/composite shaders)
// ============================================
#ifndef COMPUTE_SHADER

// ============================================
// FUNÇÃO DE SOMBRA PARA LUZ DE BLOCO (ray marching)
// ============================================
float getBlockLightShadow(vec3 worldPos, vec3 lightPos, float radius, vec3 normal) {
    vec3 toLight = lightPos - worldPos;
    float dist = length(toLight);

    if (dist > radius) return 0.0;

    vec3 lightDir = toLight / dist;

    float NdotL = dot(normal, lightDir);
    if (NdotL <= 0.0) return 0.0;

    float shadow = 1.0;
    float stepSize = max(0.3, dist / 24.0);
    vec3 currentPos = worldPos;

    for (float t = stepSize; t < dist; t += stepSize) {
        currentPos += lightDir * stepSize;

        vec4 viewPos_current = gbufferModelView * vec4(currentPos, 1.0);
        vec4 clipPos = gbufferProjection * viewPos_current;
        vec3 ndcPos = clipPos.xyz / clipPos.w;
        vec2 screenPos = ndcPos.xy * 0.5 + 0.5;

        if (screenPos.x >= 0.0 && screenPos.x <= 1.0 &&
            screenPos.y >= 0.0 && screenPos.y <= 1.0) {
            float depth = texture(depthtex0, screenPos).r;
            if (depth < 1.0) {
                vec3 ndc = vec3(screenPos, depth) * 2.0 - 1.0;
                vec4 viewPos4 = gbufferProjectionInverse * vec4(ndc, 1.0);
                vec3 viewPos = viewPos4.xyz / viewPos4.w;

                if (viewPos.z > viewPos_current.z + 0.01) {
                    shadow = 0.0;
                    break;
                }
            }
        }
    }

    return shadow;
}

// ============================================
// CALCULA ILUMINAÇÃO DE BLOCOS COM SOMBRA
// Retorna em shadowed a luz com oclusão, e em unshadowed a luz máxima (sem sombra)
// ============================================
void calculateBlockLighting(vec3 worldPos, vec3 normal, out vec3 shadowed, out vec3 unshadowed) {
    shadowed = vec3(0.0);
    unshadowed = vec3(0.0);

    uint count = min(blockLights.lightCount, MAX_BLOCKLIGHTS);

    for (uint i = 0u; i < count; i++) {
        BlockLight light = blockLights.lights[i];

        vec3 toLight = light.position - worldPos;
        float dist = length(toLight);

        if (dist > light.radius) continue;

        float atten = 1.0 - (dist / light.radius);
        atten = atten * atten;

        vec3 contrib = light.color * light.intensity * atten;
        unshadowed += contrib;

        float shadow = getBlockLightShadow(worldPos, light.position, light.radius, normal);
        shadowed += contrib * shadow;
    }
}

#endif // COMPUTE_SHADER

#endif // BLOCKLIGHT_SHADOW_GLSL

// ============================================
// CONFIGURAÇÕES OTIMIZADAS
// ============================================
#define BLOCK_LIGHTS
#define COLOURED_LIGHTS_RENDER_DISTANCE 16
#define COLOURED_LIGHTS_RENDER_DISTANCE_VERTICAL 16
#define MAX_COLOURED_LIGHTS 128
#define COLOUR_INTENSITY 1.5

// ============================================
// ESTRUTURAS OTIMIZADAS (alinhamento para cache)
// ============================================
struct LightColourBlock {
    ivec3 blockPos;
    uint lightID;
};

struct LightData {
    vec3 position;
    vec3 colour;
    float intensity;
    float radius;
    bool natural;
};

// ============================================
// CONSTANTES PRÉ-CALCULADAS
// ============================================
const uint maxChunks = COLOURED_LIGHTS_RENDER_DISTANCE;
const uint maxVerticalChunks = COLOURED_LIGHTS_RENDER_DISTANCE_VERTICAL;
const uint localBlockOffset = (maxChunks / 2) * 16;
const uint localBlockVerticalOffset = (maxVerticalChunks / 2) * 16;
const uint maxColouredLightsChunk = MAX_COLOURED_LIGHTS;
const vec3 centreOffset = vec3(0.5);
const float midblockUnit = 64.0;

// ============================================
// BUFFERS (mantidos)
// ============================================
layout (std430, binding = 16) coherent buffer positionsCheckedBuffer {
    uint[] positionsChecked;
};

layout(std430, binding = 17) coherent buffer lightColoursBuffer {
    uint[maxChunks][maxVerticalChunks][maxChunks] sizes;
    LightColourBlock[][maxColouredLightsChunk] lights;
} lightColours;

// ============================================
// FUNÇÕES DE POSIÇÃO OTIMIZADAS
// ============================================

ivec3 worldPosToBlockPos(vec3 worldPos, vec3 midBlock) {
    return ivec3(floor(worldPos + (midBlock / midblockUnit)));
}

ivec3 blockPosToChunkPos(ivec3 blockPos) {
    return blockPos >> 4; // Equivalente a floor(blockPos / 16) (mais rápido)
}

ivec3 blockPosToLocalPos(ivec3 blockPos) {
    ivec3 cameraBlockPos = ivec3(floor(cameraPosition));
    return ivec3(
        blockPos.x - cameraBlockPos.x + int(localBlockOffset),
                 blockPos.y - cameraBlockPos.y + int(localBlockVerticalOffset),
                 blockPos.z - cameraBlockPos.z + int(localBlockOffset)
    );
}

bool localChunkPosOutOfBounds(ivec3 localChunkPos) {
    return (localChunkPos.x < 0 || localChunkPos.y < 0 || localChunkPos.z < 0 ||
    localChunkPos.x >= int(maxChunks) ||
    localChunkPos.y >= int(maxVerticalChunks) ||
    localChunkPos.z >= int(maxChunks));
}

// ============================================
// POS MARKED OTIMIZADO (com early exit)
// ============================================

bool posMarked(ivec3 localBlockPos) {
    ivec3 localChunkPos = blockPosToChunkPos(localBlockPos);
    if (localChunkPosOutOfBounds(localChunkPos)) {
        return true;
    }

    // Otimização: Pré-calcula índices
    uint sector = uint(((localBlockPos.y & 15) * 8) + ((localBlockPos.z & 15) >> 1));
    uint positionsCheckedIndex = ((localChunkPos.x * maxVerticalChunks + localChunkPos.y) * maxChunks + localChunkPos.z) * 128 + sector;

    if (positionsCheckedIndex >= positionsChecked.length()) {
        return true;
    }

    uint bit = uint((localBlockPos.x & 15) + ((localBlockPos.z & 1) << 4));
    uint bitmask = 1u << bit;

    // Early exit: se já está marcado
    if ((positionsChecked[positionsCheckedIndex] & bitmask) != 0u) {
        return true;
    }

    // Atomic OR para marcar
    uint original = atomicOr(positionsChecked[positionsCheckedIndex], bitmask);
    return ((original & bitmask) != 0u);
}

// ============================================
// APPLY COLOURED LIGHT OTIMIZADO
// ============================================

vec4 applyColouredLight(vec4 baseColour, vec4 startLight, vec3 worldPos, ivec3 localChunkPos) {
    if (localChunkPosOutOfBounds(localChunkPos)) {
        baseColour *= startLight;
        return baseColour;
    }

    vec3 colours = vec3(0.0);
    float colourCount = 0.0;
    float maxWeight = 0.0;

    // Otimização: Loop desenrolado parcialmente
    for (int x = -1; x <= 1; x++) {
        for (int y = -1; y <= 1; y++) {
            for (int z = -1; z <= 1; z++) {
                ivec3 chunk = localChunkPos + ivec3(x, y, z);
                if (localChunkPosOutOfBounds(chunk)) continue;

                uint size = lightColours.sizes[chunk.x][chunk.y][chunk.z];
                if (size == 0u) continue; // Early exit se não há luzes

                uint chunkIndex = uint(chunk.x + int(maxChunks) * (chunk.y + int(maxVerticalChunks) * chunk.z));
                uint maxIndex = min(size, maxColouredLightsChunk);

                for (uint i = 0u; i < maxIndex; i++) {
                    LightColourBlock lightBlock = lightColours.lights[chunkIndex][i];

                    // Pula se lightID for inválido
                    if (lightBlock.lightID >= colouredLights.length()) continue;

                    ColouredLight light = colouredLights[lightBlock.lightID];
                    vec3 lightPos = vec3(lightBlock.blockPos) + centreOffset;

                    // Otimização: Manhattan distance com early exit
                    float dx = abs(lightPos.x - worldPos.x);
                    if (dx >= light.blockLightLevel) continue;
                    float dy = abs(lightPos.y - worldPos.y);
                    if (dy >= light.blockLightLevel) continue;
                    float dz = abs(lightPos.z - worldPos.z);
                    if (dz >= light.blockLightLevel) continue;

                    float d = dx + dy + dz;
                    if (d < light.blockLightLevel) {
                        float weight = ((light.blockLightLevel - d) / light.blockLightLevel) * COLOUR_INTENSITY;
                        float weightSq = weight * weight;
                        colours += light.lightColour * weightSq;
                        colourCount += weight;
                        maxWeight = max(maxWeight, weight);

                        if (!light.natural) {
                            startLight = max(startLight, vec4(weight));
                        }
                    }
                }
            }
        }
    }

    // Aplica luz base
    baseColour *= startLight;

    // Aplica luz colorida (otimizado)
    if (colourCount > 0.01) {
        vec3 averageColour = colours / colourCount;
        baseColour += baseColour * vec4(averageColour, 0.0);
    }

    return baseColour;
}

// ============================================
// VERSÃO OTIMIZADA COM CACHE (mais rápida)
// ============================================

// Cache para luzes próximas (reduz cálculos)
#define LIGHT_CACHE_SIZE 16
vec3 lightCachePositions[LIGHT_CACHE_SIZE];
vec3 lightCacheColours[LIGHT_CACHE_SIZE];
float lightCacheIntensities[LIGHT_CACHE_SIZE];
int lightCacheCount = 0;

vec4 applyColouredLightCached(vec4 baseColour, vec4 startLight, vec3 worldPos, ivec3 localChunkPos) {
    if (localChunkPosOutOfBounds(localChunkPos)) {
        baseColour *= startLight;
        return baseColour;
    }

    vec3 colours = vec3(0.0);
    float colourCount = 0.0;

    // Usa cache se disponível
    for (int i = 0; i < lightCacheCount && i < LIGHT_CACHE_SIZE; i++) {
        vec3 lightPos = lightCachePositions[i];
        float dx = abs(lightPos.x - worldPos.x);
        float dy = abs(lightPos.y - worldPos.y);
        float dz = abs(lightPos.z - worldPos.z);
        float d = dx + dy + dz;

        float radius = lightCacheIntensities[i];
        if (d < radius) {
            float weight = ((radius - d) / radius) * COLOUR_INTENSITY;
            float weightSq = weight * weight;
            colours += lightCacheColours[i] * weightSq;
            colourCount += weight;
        }
    }

    baseColour *= startLight;
    if (colourCount > 0.01) {
        vec3 averageColour = colours / colourCount;
        baseColour += baseColour * vec4(averageColour, 0.0);
    }
    return baseColour;
}

// ============================================
// VERSÃO COM EARLY EXIT (máxima performance)
// ============================================

vec4 applyColouredLightFast(vec4 baseColour, vec4 startLight, vec3 worldPos, ivec3 localChunkPos) {
    // Early exit: se não há luzes no chunk
    if (localChunkPosOutOfBounds(localChunkPos)) {
        baseColour *= startLight;
        return baseColour;
    }

    // Verifica rapidamente se há luzes próximas
    bool hasLight = false;
    for (int x = -1; x <= 1 && !hasLight; x++) {
        for (int y = -1; y <= 1 && !hasLight; y++) {
            for (int z = -1; z <= 1 && !hasLight; z++) {
                ivec3 chunk = localChunkPos + ivec3(x, y, z);
                if (!localChunkPosOutOfBounds(chunk)) {
                    if (lightColours.sizes[chunk.x][chunk.y][chunk.z] > 0u) {
                        hasLight = true;
                    }
                }
            }
        }
    }

    if (!hasLight) {
        return baseColour * startLight;
    }

    // Se tem luz, processa normalmente
    return applyColouredLight(baseColour, startLight, worldPos, localChunkPos);
}

// ============================================
// VERTEX SHADER FUNCTIONS OTIMIZADAS
// ============================================

#ifdef VERTEX
vec3 modelToWorldSpace(vec3 modelPos) {
    vec3 viewPos = (cubyz_ModelViewMatrix * vec4(modelPos, 1.0)).xyz;
    vec3 feetPlayerPos = (gbufferModelViewInverse * vec4(viewPos, 1.0)).xyz;
    return feetPlayerPos + cameraPosition;
}

vec4 worldToClipSpace(vec3 worldPos) {
    vec3 feetPlayerPos = worldPos - cameraPosition;
    vec3 viewPos = (gbufferModelView * vec4(feetPlayerPos, 1.0)).xyz;
    return gbufferProjection * vec4(viewPos, 1.0);
}

void registerPos(ivec3 blockPos, uint id) {
    ivec3 localBlockPos = blockPosToLocalPos(blockPos);
    ivec3 localChunkPos = blockPosToChunkPos(localBlockPos);

    if (posMarked(localBlockPos)) {
        return;
    }

    // ============================================
    // REGISTRA LUZ NO BUFFER DE SOMBRAS (ray marching)
    // ============================================
    // Só executa uma vez por bloco graças ao posMarked acima
    ColouredLight light = colouredLights[id];
    registerBlockLight(vec3(blockPos) + 0.5 - cameraPosition, float(light.blockLightLevel), light.lightColour, 1.0);

    uint currentSize = lightColours.sizes[localChunkPos.x][localChunkPos.y][localChunkPos.z];
    if (currentSize >= maxColouredLightsChunk) {
        return;
    }

    uint localIndex = atomicAdd(lightColours.sizes[localChunkPos.x][localChunkPos.y][localChunkPos.z], 1u);
    if (localIndex >= maxColouredLightsChunk) {
        return;
    }

    uint chunkIndex = uint(localChunkPos.x + int(maxChunks) * (localChunkPos.y + int(maxVerticalChunks) * localChunkPos.z));
    lightColours.lights[chunkIndex][localIndex].blockPos = blockPos;
    lightColours.lights[chunkIndex][localIndex].lightID = id;
}

void lightCheck(vec3 midBlock, ivec2 mcEntity) {
    vec3 worldPos = modelToWorldSpace(cubyz_Vertex.xyz);
    ivec3 blockPos = worldPosToBlockPos(worldPos, midBlock);

    uint blockID = uint(mcEntity.x);
    uint numLights = colouredLights.length();

    // Otimização: Verifica primeiro luzes naturais
    #ifdef BLOCK_LIGHTS
    for (uint i = 0u; i < numLights; i++) {
        if (colouredLights[i].blockID == blockID) {
            registerPos(blockPos, i);
            return; // Early exit após encontrar
        }
    }
    #else
    for (uint i = 0u; i < numLights; i++) {
        if (colouredLights[i].natural && colouredLights[i].blockID == blockID) {
            registerPos(blockPos, i);
            return;
        }
    }
    #endif
}
#endif

#endif // COLOUR_COMMON_GLSL

const ivec3 workGroups = ivec3(524288, 1, 1);

layout (local_size_x = 1, local_size_y = 1) in;

void main() {
    uint id = gl_WorkGroupID.x;

    if (id < positionsChecked.length()) {
        positionsChecked[id] = 0;
    }
    if (id < maxChunks * maxVerticalChunks * maxChunks) {
        uint z = id / (maxChunks * maxVerticalChunks);
        uint y = (id / maxChunks) % maxVerticalChunks;
        uint x = id % maxChunks;
        lightColours.sizes[x][y][z] = 0;
    }

    // Limpa o buffer de luzes para sombras
    if (id == 0u) {
        blockLights.lightCount = 0u;
    }
    if (id < MAX_BLOCKLIGHTS) {
        blockLights.lights[id].position = vec3(0.0);
        blockLights.lights[id].radius = 0.0;
        blockLights.lights[id].color = vec3(0.0);
        blockLights.lights[id].intensity = 0.0;
    }
}
