#version 410 core
// Generated by irisbridge from a shaderpack source. Do not edit.
#define MC_VERSION 12100
#define MC_GL_VERSION 460
#define MC_GLSL_VERSION 460
#define MC_MIPMAP_LEVEL 4
#define MC_RENDER_QUALITY 1.0
#define MC_SHADOW_QUALITY 1.0
#define MC_HAND_DEPTH 0.125
#define MC_NORMAL_MAP
#define MC_SPECULAR_MAP
#define MAX_COLOR_BUFFERS 16
#define IS_IRIS
#define IRIS_TAG_SUPPORT 2
#define IRIS_VERSION 10800
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUNSET 2
#define MC_RENDER_STAGE_CUSTOM_SKY 3
#define MC_RENDER_STAGE_SUN 4
#define MC_RENDER_STAGE_MOON 5
#define MC_RENDER_STAGE_STARS 6
#define MC_RENDER_STAGE_VOID 7
#define MC_RENDER_STAGE_TERRAIN_SOLID 8
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 9
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 10
#define MC_RENDER_STAGE_ENTITIES 11
#define MC_RENDER_STAGE_BLOCK_ENTITIES 12
#define MC_RENDER_STAGE_DESTROY 13
#define MC_RENDER_STAGE_OUTLINE 14
#define MC_RENDER_STAGE_DEBUG 15
#define MC_RENDER_STAGE_HAND_SOLID 16
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 17
#define MC_RENDER_STAGE_TRIPWIRE 18
#define MC_RENDER_STAGE_PARTICLES 19
#define MC_RENDER_STAGE_CLOUDS 20
#define MC_RENDER_STAGE_RAIN_SNOW 21
#define MC_RENDER_STAGE_WORLD_BORDER 22
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 23
#define MC_OS_LINUX
#define MC_GL_VENDOR_INTEL
#define MC_GL_RENDERER_INTEL

// ---- Cubyz compatibility shim ----

// ---- shaderpack source ----
// Fragment GL version

#define COMPOSITE6
#define FRAGMENT

// ============================================================
//  CinematicVanilla V2 - settings.glsl
//  All user-facing toggles. Profiles (LOW/MEDIUM/HIGH) in
//  shaders.properties override these defaults at load time.
// ============================================================

/// ─── Performance Preset ─────────────────────────────────────────────────────
// profile is set by shaders.properties; individual toggles below can be
// overridden by the user in the shader menu.

/// ─── Post Processing ────────────────────────────────────────────────────────
#define OUTLINES 2               // Block outlines. 0=off 1=classic 2=dungeons [0 1 2]
#define OUTLINE_BRIGHTNESS 0.80  // [-1.00 -0.75 -0.50 -0.25 0.00 0.25 0.50 0.75 1.00]
#define OUTLINE_PIXEL_SIZE 1     // [1 2 4]

#define ANTI_ALIASING 2          // 0=off 1=FXAA 2=TAA 3=both [0 1 2 3]
// #define SHARPEN_FILTER

/// ─── Bloom ───────────────────────────────────────────────────────────────────
#define BLOOM                    // Toggle: bloom glow
#define BLOOM_STRENGTH 0.90      // [0.00 0.10 0.20 0.30 0.40 0.50 0.60 0.70 0.80 0.90 1.00]
#define BLOOM_RADIUS 4           // Blur radius in passes. High = softer, costs perf. [2 4 6 8]

/// ─── Depth of Field ─────────────────────────────────────────────────────────
// #define DOF                   // Toggle: cinematic depth of field
#define DOF_STRENGTH 2           // [1 2 3 4 5]
#define DOF_FOCAL_DIST 8.0       // Focus distance in blocks [2.0 4.0 8.0 16.0 32.0]

/// ─── Camera ─────────────────────────────────────────────────────────────────
// #define CHROMATIC_ABERRATION
#define ABERRATION_PIXEL_SIZE 2  // [1 2 4]
// #define VIGNETTE
#define VIGNETTE_STRENGTH 0.80   // [0.00 0.25 0.50 0.75 1.00 1.25 1.50]
// #define MOTION_BLUR
#define MOTION_BLUR_STRENGTH 0.75 // [0.25 0.50 0.75 1.00]

/// ─── Lens Flare ─────────────────────────────────────────────────────────────
#define LENS_FLARE
#define LENS_FLARE_STRENGTH 0.85 // [0.00 0.25 0.50 0.75 1.00 1.25 1.50]

/// ─── Tonemapping ────────────────────────────────────────────────────────────
#define CONTRAST   1.06          // [0.80 0.90 1.00 1.05 1.06 1.10 1.15 1.20]
#define SATURATION 0.93          // [0.70 0.80 0.90 0.93 1.00 1.10 1.20]
#define WHITE_POINT 2.0          // [1.0 1.5 2.0 2.5 3.0]
#define SHOULDER_STRENGTH 0.05   // [0.00 0.05 0.10 0.15 0.20]
// #define AUTO_EXPOSURE
#define EXPOSURE 1.00            // [0.50 0.75 1.00 1.25 1.50]

#define TINT_R 255
#define TINT_G 255
#define TINT_B 255

/// ─── Lighting ───────────────────────────────────────────────────────────────
#define SHADOW_MAPPING
#define SHADOW_FILTER            // Soft shadows (PCSS-style noise)
#define SHADOW_COLOR             // Transparent-object shadow tinting
#define SHADOW_RESOLUTION 2048   // [1024 2048 4096]  (profile overrides)

// Contact shadows: cheap screen-space rim darkening at geometry edges
// #define CONTACT_SHADOWS        // Toggle
#define CONTACT_SHADOW_STEPS 8   // [4 8 12 16]
#define CONTACT_SHADOW_RADIUS 0.4 // Screen radius [0.1 0.2 0.4 0.6]

#define ENTITY_SHADOWS
#define BLOCK_ENTITY_SHADOWS

const float sunPathRotation = 30.0; // [-60.0 -45.0 -30.0 -15.0 0.0 15.0 30.0 45.0 60.0]

#define UNDERWATER_CAUSTICS 1    // [0 1 2]
#define SSAO                     // Screen-space ambient occlusion
#define AMBIENT_LIGHTING 0.06    // [0.00 0.03 0.06 0.10 0.15 0.20]

/// ─── Global Illumination / Reflections ──────────────────────────────────────
// #define SSGI
#define SSR                      // Screen-space reflections
#define RAYTRACER_STEPS 20       // [16 20 24 32]
#define RAYTRACER_BISTEPS 2      // [0 2 4 6]
// #define ROUGH_REFLECTIONS
#define PREVIOUS_FRAME

/// ─── God Rays ────────────────────────────────────────────────────────────────
#define GOD_RAYS                 // Toggle: sun/moon volumetric shafts
#define GOD_RAY_STEPS 8          // [4 8 12 16]  (LOW uses 0 = disabled)
#define GOD_RAY_STRENGTH 0.55    // [0.10 0.25 0.55 0.75 1.00]

/// ─── Atmospherics ───────────────────────────────────────────────────────────
#define SUN_MOON_TYPE 0          // [0 1 2]
#define SUN_MOON_INTENSITY 4     // [0 1 2 3 4 5 6]

#define VOLUMETRIC_LIGHTING
#define VOLUMETRIC_LIGHTING_STRENGTH 0.50 // [0.00 0.10 0.20 0.30 0.40 0.50 0.60 0.70]

/// ─── Cinematic Fog ──────────────────────────────────────────────────────────
#define CINEMATIC_FOG            // Toggle: distance + height based fog
#define BORDER_FOG
#define GROUND_FOG_STRENGTH 0.55 // [0.00 0.10 0.25 0.40 0.55 0.70 0.85 1.00]
#define SKYBOX_BRIGHTNESS 1.00   // [0.50 0.75 1.00 1.25 1.50]

/// ─── Clouds ─────────────────────────────────────────────────────────────────
#define CLOUD_TYPE 2             // 0=off 1=vanilla 2=volumetric [0 1 2]
#define DOUBLE_LAYERED_CLOUDS
#define DYNAMIC_CLOUDS
#define FADE_SPEED 0.20          // [0.05 0.10 0.20 0.30 0.40]
#define SECOND_CLOUD_HEIGHT 128.0 // [64.0 96.0 128.0 160.0 192.0 256.0]
#define VOLUMETRIC_CLOUD_STEPS 16 // [8 16 32 64]   (HIGH = 32)
#define VOLUMETRIC_CLOUD_DEPTH 8.0 // [4.0 6.0 8.0 10.0 12.0]
#define SKYBOX_CLOUD_STEPS 16    // [8 16 32 64]
#define SKYBOX_CLOUD_DEPTH 0.08  // [0.02 0.04 0.08 0.12 0.16]

/// ─── Water ──────────────────────────────────────────────────────────────────
#define WATER_WAVE_QUALITY 1     // 0=flat 1=medium 2=high [0 1 2]
#define WATER_DEPTH_TINT         // Toggle: depth-based color absorption
#define WATER_DEPTH_COLOR vec3(0.04, 0.20, 0.30) // Shallow → deep color
#define WATER_DEPTH_SCALE 0.20   // Absorption per meter [0.05 0.10 0.20 0.35]
#define UNDERWATER_BLUR          // Toggle: underwater distortion effect

/// ─── Wet Surfaces ───────────────────────────────────────────────────────────
#define WET_SURFACES             // Toggle: rain darkens & adds specularity
#define WET_PUDDLES              // Toggle: animated puddle ripples in rain

/// ─── Wind ───────────────────────────────────────────────────────────────────
#define WIND_QUALITY 1           // 0=off 1=simple 2=gusting [0 1 2]
#define WIND_SPEED 1.0           // [0.0 0.5 1.0 1.5 2.0]
#define WIND_FREQUENCY 1.0       // [0.5 1.0 1.5 2.0]
#define CURRENT_SPEED 1.0
#define CURRENT_FREQUENCY 0.5

// ============================================================
//  CinematicVanilla V3 — New Settings
// ============================================================

/// ─── Seasonal Preset ────────────────────────────────────────────────────────
// Changes the color grade to match a season's mood.
// None = classic CinematicVanilla look
#define SEASONAL_PRESET 0        // 0=None 1=Summer 2=Autumn 3=Winter 4=Spring [0 1 2 3 4]

/// ─── Poster Mode ────────────────────────────────────────────────────────────
// Activates an aggressive cinematic grade designed for screenshots.
// Stronger teal-orange split tone, boosted contrast & saturation,
// cinematic letterbox bars, and enhanced film grain.
// Toggle ON/OFF in shader menu. Does NOT affect gameplay performance.
// #define POSTER_MODE

/// ─── Film Halation ──────────────────────────────────────────────────────────
// Warm red-orange glow on bright highlights — vintage film emulsion effect.
// Already ON in Poster Mode. Can be enabled separately here.
// #define FILM_HALATION

/// ─── Letterbox (Poster Mode bars) ───────────────────────────────────────────
#define LETTERBOX_STRENGTH 0.10  // Height of bars as fraction of screen [0.05 0.08 0.10 0.12 0.15 0.20]
// --------------- Code Library ---------------- //
// Common utility functions goes here

#define PI 3.14159265
#define TAU 6.28318531
#define GOLDEN_RATIO 1.61803399

// Certain RP artists mistakingly add additional alpha to nontranslucent textures
#define ALPHA_THRESHOLD 0.1

const float lightMapEpsilon = 1.0 / 16.0;
const float lightMapVertexScale = 1.0328125 / 240.0;
const float oneMinusLightMapScale = 1.0 - lightMapEpsilon;

// For some reason, the lightmap has precision errors and does not reach 0 or 1
float lightMapCoord(in float lightMap){
	// lightMap = (lightMap * 33.05 / 32.0) - (1.05 / 32.0);
	lightMap = lightMap * lightMapVertexScale - 0.0328125;

	if(lightMap < lightMapEpsilon) return 0.0;
	if(lightMap > oneMinusLightMapScale) return 1.0;

	return lightMap;
}

vec2 lightMapCoord(in vec2 lightMap){
	return vec2(lightMapCoord(lightMap.x), lightMapCoord(lightMap.y));
}

// Saturate/clamp functions
float saturate(in float x){ return clamp(x, 0.0, 1.0); }
vec2 saturate(in vec2 x){ return clamp(x, vec2(0), vec2(1)); }
vec3 saturate(in vec3 x){ return clamp(x, vec3(0), vec3(1)); }
vec4 saturate(in vec4 x){ return clamp(x, vec4(0), vec4(1)); }

// Sum functions
float sumOf(in vec2 x){ return x.x + x.y; }
float sumOf(in vec3 x){ return x.x + x.y + x.z; }
float sumOf(in vec4 x){ return x.x + x.y + x.z + x.w; }

// Squared functions x ^ 2
float squared(in float x){ return x * x; }
vec2 squared(in vec2 x){ return x * x; }
vec3 squared(in vec3 x){ return x * x; }
vec4 squared(in vec4 x){ return x * x; }

// Cubed functions x^3
float cubed(in float x){ return x * x * x; }
vec2 cubed(in vec2 x){ return x * x * x; }
vec3 cubed(in vec3 x){ return x * x * x; }
vec4 cubed(in vec4 x){ return x * x * x; }

// Length squared
float lengthSquared(in vec2 x){ return dot(x, x); }
float lengthSquared(in vec3 x){ return dot(x, x); }
float lengthSquared(in vec4 x){ return dot(x, x); }

// Faster normalize using inversesqrt()
vec2 fastNormalize(in vec2 x){ return x * inversesqrt(lengthSquared(x)); }
vec3 fastNormalize(in vec3 x){ return x * inversesqrt(lengthSquared(x)); }
vec4 fastNormalize(in vec4 x){ return x * inversesqrt(lengthSquared(x)); }

// Min functions
float minOf(in vec2 x){ return min(x.x, x.y); }
float minOf(in vec3 x){ return min(x.x, min(x.y, x.z)); }
float minOf(in vec4 x){ return min(min(x.x, x.y), min(x.z, x.w)); }

// Unsigned min functions
uint minOf(in uvec2 x){ return min(x.x, x.y); }
uint minOf(in uvec3 x){ return min(x.x, min(x.y, x.z)); }
uint minOf(in uvec4 x){ return min(min(x.x, x.y), min(x.z, x.w)); }

// Max functions
float maxOf(in vec2 x){ return max(x.x, x.y); }
float maxOf(in vec3 x){ return max(x.x, max(x.y, x.z)); }
float maxOf(in vec4 x){ return max(max(x.x, x.y), max(x.z, x.w)); }

// Unsigned max functions
uint maxOf(in uvec2 x){ return max(x.x, x.y); }
uint maxOf(in uvec3 x){ return max(x.x, max(x.y, x.z)); }
uint maxOf(in uvec4 x){ return max(max(x.x, x.y), max(x.z, x.w)); }

// Linear interpolation functions
float lerp(float a, float b, float c, float d){
	if(d < 1) return mix(a, b, d);
    return mix(b, c, d - 1.0);
}

vec3 lerp(vec3 a, vec3 b, vec3 c, float d){
	if(d < 1) return mix(a, b, d);
    return mix(b, c, d - 1.0);
}

// Hermite interpolation
float hermiteMix(in float a, in float b, in float x){ return (x - a) / (b - a); }
vec2 hermiteMix(in float a, in float b, in vec2 x){ return (x - a) / (b - a); }
vec3 hermiteMix(in float a, in float b, in vec3 x){ return (x - a) / (b - a); }
vec4 hermiteMix(in float a, in float b, in vec4 x){ return (x - a) / (b - a); }
vec2 hermiteMix(in vec2 a, in vec2 b, in vec2 x){ return (x - a) / (b - a); }
vec3 hermiteMix(in vec3 a, in vec3 b, in vec3 x){ return (x - a) / (b - a); }
vec4 hermiteMix(in vec4 a, in vec4 b, in vec4 x){ return (x - a) / (b - a); }

// Fast approximate sqrt for 0-1 range
float fastSqrt(in float x){ return x * (2.0 - x); }
vec2 fastSqrt(in vec2 x){ return x * (2.0 - x); }
vec3 fastSqrt(in vec3 x){ return x * (2.0 - x); }
vec4 fastSqrt(in vec4 x){ return x * (2.0 - x); }

// Smoothstep functions
float smoothen(in float x){ return x * x * (3.0 - 2.0 * x); }
vec2 smoothen(in vec2 x){ return x * x * (3.0 - 2.0 * x); }
vec3 smoothen(in vec3 x){ return x * x * (3.0 - 2.0 * x); }
vec4 smoothen(in vec4 x){ return x * x * (3.0 - 2.0 * x); }

// Smootherstep functions
float smootherstep(in float x){ return x * x * x * (x * (x * 6.0 - 15.0) + 10.0); }
vec2 smootherstep(in vec2 x){ return x * x * x * (x * (x * 6.0 - 15.0) + 10.0); }
vec3 smootherstep(in vec3 x){ return x * x * x * (x * (x * 6.0 - 15.0) + 10.0); }
vec4 smootherstep(in vec4 x){ return x * x * x * (x * (x * 6.0 - 15.0) + 10.0); }

vec2 getMatScale(in mat2 matrix){
	return vec2(matrix[0].x, matrix[1].y);
}

vec3 getMatScale(in mat3 matrix){
	return vec3(matrix[0].x, matrix[1].y, matrix[2].z);
}

vec4 getMatScale(in mat4 matrix){
	return vec4(matrix[0].x, matrix[1].y, matrix[2].z, matrix[3].w);
}

// By Jessie#7257
vec3 generateUnitVector(in vec2 hash){
    hash.x *= TAU; hash.y = hash.y * 2.0 - 1.0;
    return vec3(vec2(cos(hash.x), sin(hash.x)) * sqrt(1.0 - hash.y * hash.y), hash.y);
}

vec3 generateCosineVector(in vec3 vector, in vec3 noiseUnitVector){
	vec3 vectorDir = fastNormalize(vector + noiseUnitVector);
	return dot(vectorDir, vector) < 0 ? -vectorDir : vectorDir;
}

// Rotation functions
mat2 rot2D(in float x){
	float cosX = cos(x);
  	float sinX = sin(x);

	return mat2(
		cosX, -sinX, 
		sinX, cosX
	);
}

// Rotate on the x axis
mat3 rot3DX(in float x){
	float cosX = cos(x);
  	float sinX = sin(x);

	return mat3(
		cosX, -sinX, 0,
		sinX, cosX, 0,
		0, 0, 1
	);
}

// Rotate on the y axis
mat3 rot3DY(in float y){
	float cosY = cos(y);
  	float sinY = sin(y);

	return mat3(
		cosY, 0, sinY,
		0, 1, 0,
		-sinY, 0, cosY
	);
}

// Rotate on the z axis
mat3 rot3DZ(in float z){
	float cosZ = cos(z);
  	float sinZ = sin(z);

	return mat3(
		1, 0, 0,
		0, cosZ, -sinZ,
		0, sinZ, cosZ
	);
}

// SRGB to linear
float toLinear(in float x){ return ((2.10545 + x) * (0.0231872 + x)) * x * 0.315206; }
vec3 toLinear(in vec3 x){ return ((2.10545 + x) * (0.0231872 + x)) * x * 0.315206; }

// Linear to SRGB
float toSRGB(in float x){ return (inversesqrt(x) - 0.126893) * x * 1.14374; }
vec3 toSRGB(in vec3 x){ return (inversesqrt(x) - 0.126893) * x * 1.14374; }

/*
// SRGB to linear
float toLinear(in float x){ return pow(x, vec3(2.2)); }
vec3 toLinear(in vec3 x){ return pow(x, 2.2); }

// Linear to sRGB
float toSRGB(in float x){ return pow(x, vec3(1.0 / 2.2)); }
vec3 toSRGB(in vec3 x){ return pow(x, 1.0 / 2.2); }

// SRGB to linear
float toLinear(in float x){ return ((2.10545 + x) * (0.0231872 + x)) * x * 0.315206; }
vec3 toLinear(in vec3 x){ return ((2.10545 + x) * (0.0231872 + x)) * x * 0.315206; }

// Linear to SRGB
float toSRGB(in float x){ return (inversesqrt(x) - 0.126893) * x * 1.14374; }
vec3 toSRGB(in vec3 x){ return (inversesqrt(x) - 0.126893) * x * 1.14374; }
*/

/* --Main world/dimension settings-- */

/* This file allows custom macro settings for multiple worlds/dimensions,
allowing more compatibility for future worlds/dimensions and modded worlds/dimensions */

// Initial dimension id
#define WORLD_ID 0

// Enable if your world uses default shader lighting from the sun/moon
#define WORLD_LIGHT
// Enable sun/moon in your world. 1 for the standard sun and moon. 2 for the black hole.
#define WORLD_SUN_MOON 1
// Sun/moon size
#define WORLD_SUN_MOON_SIZE 0.1

// Force disable clouds
// #define FORCE_DISABLE_CLOUDS
// Force disable weather
// #define FORCE_DISABLE_WEATHER
// Force disable day cycle
// #define FORCE_DISABLE_DAY_CYCLE

// Enable aether particles in your world
// #define WORLD_AETHER
// Enable sky ground
#define WORLD_SKY_GROUND

// Use a sky light amount if your world has an undefined sky lighting environment like The End or the Nether
// #define WORLD_CUSTOM_SKYLIGHT 1.00

// Enable stars in your world
#define WORLD_STARS toLinear(4.0 - dayCycle * 2.0)

// If the world utilizes vanilla sky color
// #define WORLD_VANILLA_FOG_COLOR
// Enable if your world uses a specific world color that uses the vanilla fog color, overrides sky colors
// #define WORLD0_VANILLA_FOGCOLI 1.00 // Intensity value [0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80 1.85 1.90 1.95 2.00]

#define FOG0_VERTICAL_DENSITY_D 0.080 // Vertical density falloff, larger means thinner fog at high altitudes, but thicker fog in low altitudes [0.005 0.010 0.015 0.020 0.025 0.030 0.035 0.040 0.045 0.050 0.055 0.060 0.065 0.070 0.075 0.080 0.085 0.090 0.095 0.100 0.105 0.110 0.115 0.120 0.125 0.130 0.135 0.140 0.145 0.150 0.155 0.160 0.165 0.170 0.175 0.180 0.185 0.190 0.195 0.200 0.205 0.210 0.215 0.220 0.225 0.230 0.235 0.240 0.245 0.250 0.255 0.260 0.265 0.270 0.275 0.280 0.285 0.290 0.295 0.300 0.305 0.310 0.315 0.320 0.325 0.330 0.335 0.340 0.345 0.350 0.355 0.360 0.365 0.370 0.375 0.380 0.385 0.390 0.395 0.40 0.405 0.410 0.415 0.420 0.425 0.430 0.435 0.440 0.445 0.450 0.455 0.460 0.465 0.470 0.475 0.480 0.485 0.490 0.495 0.500]
#define FOG0_VERTICAL_DENSITY_N 0.020 // Vertical density falloff, larger means thinner fog at high altitudes, but thicker fog in low altitudes [0.005 0.010 0.015 0.020 0.025 0.030 0.035 0.040 0.045 0.050 0.055 0.060 0.065 0.070 0.075 0.080 0.085 0.090 0.095 0.100 0.105 0.110 0.115 0.120 0.125 0.130 0.135 0.140 0.145 0.150 0.155 0.160 0.165 0.170 0.175 0.180 0.185 0.190 0.195 0.200 0.205 0.210 0.215 0.220 0.225 0.230 0.235 0.240 0.245 0.250 0.255 0.260 0.265 0.270 0.275 0.280 0.285 0.290 0.295 0.300 0.305 0.310 0.315 0.320 0.325 0.330 0.335 0.340 0.345 0.350 0.355 0.360 0.365 0.370 0.375 0.380 0.385 0.390 0.395 0.40 0.405 0.410 0.415 0.420 0.425 0.430 0.435 0.440 0.445 0.450 0.455 0.460 0.465 0.470 0.475 0.480 0.485 0.490 0.495 0.500]
#define FOG0_VERTICAL_DENSITY_T 0.040 // Vertical density falloff, larger means thinner fog at high altitudes, but thicker fog in low altitudes [0.005 0.010 0.015 0.020 0.025 0.030 0.035 0.040 0.045 0.050 0.055 0.060 0.065 0.070 0.075 0.080 0.085 0.090 0.095 0.100 0.105 0.110 0.115 0.120 0.125 0.130 0.135 0.140 0.145 0.150 0.155 0.160 0.165 0.170 0.175 0.180 0.185 0.190 0.195 0.200 0.205 0.210 0.215 0.220 0.225 0.230 0.235 0.240 0.245 0.250 0.255 0.260 0.265 0.270 0.275 0.280 0.285 0.290 0.295 0.300 0.305 0.310 0.315 0.320 0.325 0.330 0.335 0.340 0.345 0.350 0.355 0.360 0.365 0.370 0.375 0.380 0.385 0.390 0.395 0.40 0.405 0.410 0.415 0.420 0.425 0.430 0.435 0.440 0.445 0.450 0.455 0.460 0.465 0.470 0.475 0.480 0.485 0.490 0.495 0.500]

#define FOG0_TOTAL_DENSITY 0.005 // Total density falloff, larger means thicker fog [0.005 0.010 0.015 0.020 0.025 0.030 0.035 0.040 0.045 0.050 0.055 0.060 0.065 0.070 0.075 0.080 0.085 0.090 0.095 0.100 0.105 0.110 0.115 0.120 0.125 0.130 0.135 0.140 0.145 0.150 0.155 0.160 0.165 0.170 0.175 0.180 0.185 0.190 0.195 0.200 0.205 0.210 0.215 0.220 0.225 0.230 0.235 0.240 0.245 0.250 0.255 0.260 0.265 0.270 0.275 0.280 0.285 0.290 0.295 0.300 0.305 0.310 0.315 0.320 0.325 0.330 0.335 0.340 0.345 0.350 0.355 0.360 0.365 0.370 0.375 0.380 0.385 0.390 0.395 0.40 0.405 0.410 0.415 0.420 0.425 0.430 0.435 0.440 0.445 0.450 0.455 0.460 0.465 0.470 0.475 0.480 0.485 0.490 0.495 0.500]

// For the shader to read
#define FOG_VERTICAL_DENSITY lerp(FOG0_VERTICAL_DENSITY_N, FOG0_VERTICAL_DENSITY_T, FOG0_VERTICAL_DENSITY_D, dayCycle)
#define FOG_TOTAL_DENSITY FOG0_TOTAL_DENSITY

// Day colors
#define LIGHT0_DR 255 // Red value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_DG 195 // CinematicVanilla: slightly warmer golden sunlight // Green value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_DB 140 // CinematicVanilla: warmer less-blue sunlight // Blue value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_DI 1.35 // CinematicVanilla: slightly brighter day // Intensity value [0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80 1.85 1.90 1.95 2.00]

const vec3 lightDayColor = vec3(LIGHT0_DR, LIGHT0_DG, LIGHT0_DB) * (LIGHT0_DI * 0.00392156863);

#define SKY0_DR 36  // CinematicVanilla: deeper sky // Red value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_DG 96  // CinematicVanilla: richer azure // Green value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_DB 180 // CinematicVanilla: more vivid blue sky // Blue value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_DI 1.35 // CinematicVanilla // Intensity value [0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80 1.85 1.90 1.95 2.00]

const vec3 skyDayColor = vec3(SKY0_DR, SKY0_DG, SKY0_DB) * (SKY0_DI * 0.00392156863);

// Night colors
#define LIGHT0_NR 42  // CinematicVanilla // Red value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_NG 108 // CinematicVanilla: cool moonlight // Green value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_NB 162 // CinematicVanilla: bluer moonlight // Blue value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_NI 1.00 // Intensity value [0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80 1.85 1.90 1.95 2.00]

const vec3 lightNightColor = vec3(LIGHT0_NR, LIGHT0_NG, LIGHT0_NB) * (LIGHT0_NI * 0.00392156863);

#define SKY0_NR 3   // CinematicVanilla: deep indigo night // Red value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_NG 18  // CinematicVanilla: less green at night // Green value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_NB 105 // CinematicVanilla: deep indigo // Blue value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_NI 0.90 // CinematicVanilla: darker night sky // Intensity value [0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80 1.85 1.90 1.95 2.00]

const vec3 skyNightColor = vec3(SKY0_NR, SKY0_NG, SKY0_NB) * (SKY0_NI * 0.00392156863);

// Twilight colors
#define LIGHT0_TR 255 // CinematicVanilla: rich sunset // Red value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_TG 138 // CinematicVanilla: deeper sunset amber // Green value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_TB 48  // CinematicVanilla: less blue at sunset // Blue value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define LIGHT0_TI 1.40 // CinematicVanilla: vivid sunset light // Intensity value [0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80 1.85 1.90 1.95 2.00]

const vec3 lightTwilightColor = vec3(LIGHT0_TR, LIGHT0_TG, LIGHT0_TB) * (LIGHT0_TI * 0.00392156863);

#define SKY0_TR 90  // CinematicVanilla: peachy sunset sky // Red value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_TG 42  // CinematicVanilla // Green value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_TB 99  // CinematicVanilla: warm twilight sky // Blue value [3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 102 105 108 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216 219 222 225 228 231 234 237 240 243 246 249 252 255]
#define SKY0_TI 1.10 // CinematicVanilla: brighter twilight sky // Intensity value [0.00 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 1.00 1.05 1.10 1.15 1.20 1.25 1.30 1.35 1.40 1.45 1.50 1.55 1.60 1.65 1.70 1.75 1.80 1.85 1.90 1.95 2.00]

const vec3 skyTwilightColor = vec3(SKY0_TR, SKY0_TG, SKY0_TB) * (SKY0_TI * 0.00392156863);

// Holds the data on how the light will change according to multiple environmental factors
#define SUN_COL_DATA_BLOCK mix(lightTwilightColor, lightDayColor, twilightPhase)
#define MOON_COL_DATA_BLOCK lightNightColor

#define LIGHT_COLOR_DATA_BLOCK0 (dayCycle > 1 ? mix(lightTwilightColor, lightDayColor, twilightPhase) : lightNightColor)
#define LIGHT_COLOR_DATA_BLOCK1(S, M) (dayCycle > 1 ? S : M)

#define SKY_COLOR_DATA_BLOCK lerp(skyNightColor, skyTwilightColor, skyDayColor, dayCycle)
/*
================================ /// Super Duper Vanilla v1.3.8 /// ================================

    Developed by Eldeston, presented by FlameRender (C) Studios.

    Copyright (C) 2023 Eldeston | FlameRender (C) Studios License


    By downloading this content you have agreed to the license and its terms of use.

================================ /// Super Duper Vanilla v1.3.8 /// ================================
*/

/// Buffer features: Lens flare, applied bloom, auto exposure, tonemapping, vignette and postColOut grading

/// -------------------------------- /// Vertex Shader /// -------------------------------- ///

#ifdef VERTEX
    #if defined LENS_FLARE && defined WORLD_LIGHT
        flat out vec3 sRGBLightCol;
        flat out vec3 shdLightDirScreenSpace;
    #endif

    noperspective out vec2 texCoord;

    #if defined LENS_FLARE && defined WORLD_LIGHT
        uniform mat4 gbufferProjection;

        uniform mat4 gbufferModelView;

        uniform mat4 shadowModelView;

        #ifndef FORCE_DISABLE_WEATHER
            uniform float rainStrength;
        #endif

        #ifndef FORCE_DISABLE_DAY_CYCLE
            uniform float dayCycle;
            uniform float twilightPhase;
        #endif

        // Screen space to view space perspective projection
vec3 getViewPos(in mat4 projectionInverse, in vec3 screenPos){
	// vec3 viewPos = vec3(vec2(projectionInverse[0].x, projectionInverse[1].y) * (screenPos.xy * 2.0 - 1.0), -1);
    // return viewPos / (projectionInverse[2].w * (screenPos.z * 2.0 - 1.0) + projectionInverse[3].w);
    vec3 viewPos = vec3(vec2(projectionInverse[0].x, projectionInverse[1].y) * screenPos.xy * 2.0 - vec2(projectionInverse[0].x, projectionInverse[1].y), -1);
    return viewPos / (projectionInverse[2].w * screenPos.z * 2.0 - projectionInverse[2].w + projectionInverse[3].w);
}

// Screen depth to view depth
float getViewDepth(in mat4 projectionInverse, in float screenDepth){
	// return -1.0 / (projectionInverse[2].w * (screenDepth * 2.0 - 1.0) + projectionInverse[3].w);
	return -1.0 / (projectionInverse[2].w * screenDepth * 2.0 - projectionInverse[2].w + projectionInverse[3].w);
}

// View space to screen space perspective projection
vec3 getScreenPos(in mat4 projection, in vec3 viewPos){
	// vec3 screenPos = vec3(projection[0].x, projection[1].y, projection[2].z) * viewPos;
	// return (vec3(screenPos.xy, screenPos.z + projection[3].z) / -viewPos.z) * 0.5 + 0.5;
    vec2 clipCoord = vec2(projection[0].x, projection[1].y) * viewPos.xy;
	return 0.5 - vec3(clipCoord.xy / viewPos.z, projection[3].z / viewPos.z + projection[2].z) * 0.5;
}

// View space to screen space coordinates perspective projection
vec2 getScreenCoord(in mat4 projection, in vec3 viewPos){
	vec2 clipCoord = vec2(projection[0].x, projection[1].y) * viewPos.xy;
	return 0.5 - (clipCoord.xy / viewPos.z) * 0.5;
}

// View depth to screen depth
float getScreenDepth(in mat4 projection, in float viewDepth){
    // ((projection[2].z * viewDepth + projection[3].z) / -viewDepth) * 0.5 + 0.5
	return 0.5 - (projection[3].z / viewDepth + projection[2].z) * 0.5;
}
    #endif

    void main(){
        texCoord = cubyz_MultiTexCoord0.xy;

        #if defined LENS_FLARE && defined WORLD_LIGHT
            // Get sRGB light postColOut
            sRGBLightCol = LIGHT_COLOR_DATA_BLOCK0;

            // Get shadow light view direction in screen space
            shdLightDirScreenSpace = vec3(getScreenCoord(gbufferProjection, mat3(gbufferModelView) * vec3(shadowModelView[0].z, shadowModelView[1].z, shadowModelView[2].z)), gbufferProjection[1].y * 0.72794047);
        #endif

        gl_Position = vec4(cubyz_Vertex.xy * 2.0 - 1.0, 0, 1);
    }
#endif

/// -------------------------------- /// Fragment Shader /// -------------------------------- ///

#ifdef FRAGMENT
    /* RENDERTARGETS: 3 */
    layout(location = 0) out vec3 postColOut; // colortex3

    #ifdef AUTO_EXPOSURE
        /* RENDERTARGETS: 3,5 */
        layout(location = 1) out vec4 temporalDataOut; // colortex5
    #endif

    #if defined LENS_FLARE && defined WORLD_LIGHT
        flat in vec3 sRGBLightCol;
        flat in vec3 shdLightDirScreenSpace;
    #endif

    noperspective in vec2 texCoord;

    uniform sampler2D colortex4;

    #ifdef AUTO_EXPOSURE
        uniform float frameTime;

        uniform sampler2D colortex5;
    #endif

    #ifdef BLOOM
        uniform float pixelWidth;
        uniform float pixelHeight;

        uniform sampler2D colortex0;

        vec3 getBloomTile(in vec2 coords, in float invScale){
            // Remap to bloom tile texture coordinates
            vec2 baseCoord = texCoord * invScale + coords;

            // Pixel size
            vec2 pixelSize = vec2(pixelWidth, pixelHeight);

            vec2 topRightCorner = baseCoord + pixelSize;
            vec2 bottomLeftCorner = baseCoord - pixelSize;

            // Apply box blur all tiles
            return textureLod(colortex0, bottomLeftCorner, 0).rgb + textureLod(colortex0, topRightCorner, 0).rgb +
                textureLod(colortex0, vec2(bottomLeftCorner.x, topRightCorner.y), 0).rgb + textureLod(colortex0, vec2(topRightCorner.x, bottomLeftCorner.y), 0).rgb;
        }
    #endif

    #if defined LENS_FLARE && defined WORLD_LIGHT
        uniform float blindness;
        uniform float darknessFactor;

        uniform float aspectRatio;

        uniform sampler2D depthtex0;

        #ifdef DISTANT_HORIZONS
            uniform sampler2D dhDepthTex1;
        #endif

        #ifndef FORCE_DISABLE_WEATHER
            uniform float rainStrength;
        #endif

        float lensShape(in vec2 lensCoord){
    #if WORLD_SUN_MOON == 2
        return abs(length(lensCoord) - cubed(WORLD_SUN_MOON_SIZE));
    #else
        return length(lensCoord) - cubed(WORLD_SUN_MOON_SIZE);
    #endif
}

float lensFlareSimple(in vec2 centerCoord, in vec2 lightDir, in float size, in float dist){
    vec2 flareCoord = centerCoord + lightDir * dist;
    return squared(squared(max(0.0, 1.0 - lensShape(vec2(flareCoord.x * aspectRatio, flareCoord.y)) / (size * shdLightDirScreenSpace.z))));
}

float lensFlareRays(in vec2 centerCoord, in vec2 lightDir, in float rayBeam, in float size, in float dist){
    vec2 flareCoord = centerCoord + lightDir * dist;
    float rays = max(0.0, sin(atan(flareCoord.x * aspectRatio, flareCoord.y) * rayBeam));
    float lens = lensFlareSimple(centerCoord, lightDir, size, dist);
    return rays * lens + lens;
}

vec3 chromaLens(in vec2 centerCoord, in vec2 lightDir, in float chromaDist, in float size, in float dist){
    return vec3(
        lensFlareSimple(centerCoord, lightDir, size, dist),
        lensFlareSimple(centerCoord, lightDir, size, dist * (1.0 - chromaDist)),
        lensFlareSimple(centerCoord, lightDir, size, dist * (1.0 - chromaDist * 2.0))
        );
}

vec3 getLensFlare(in vec2 centerCoord, in vec2 lightDir){
    float lens0 = lensFlareSimple(centerCoord, lightDir, 0.2, 0.75);
    float lens1 = lensFlareSimple(centerCoord, lightDir, 0.1, 0.5);
    float lens2 = lensFlareSimple(centerCoord, lightDir, 0.05, 0.25);
    
    vec3 chromaLens = chromaLens(centerCoord, lightDir, 0.05, 0.05, -0.5);

    #if WORLD_SUN_MOON == 2
        return (lens1 + (lens0 + lens2) * 0.125 + chromaLens) * LENS_FLARE_STRENGTH * sRGBLightCol;
    #elif SUN_MOON_TYPE == 2
        float rays = lensFlareRays(centerCoord, lightDir, 8.0, 0.05, -1.0);
        return (lens1 + (lens0 + lens2) * 0.125 + rays + chromaLens) * LENS_FLARE_STRENGTH * sRGBLightCol;
    #else
        float rays = lensFlareRays(centerCoord, lightDir, 8.0, 0.1, -1.0);
        return (lens1 + (lens0 + lens2) * 0.125 + rays + chromaLens) * LENS_FLARE_STRENGTH * sRGBLightCol;
    #endif
}
    #endif

    // Default noise resolution
const int noiseTextureResolution = 256;

// Noise sample, r for blue noise, g for white noise, and b for cell noise
uniform sampler2D noisetex;

vec3 getRng3(in ivec2 iuv){
    return vec3(texelFetch(noisetex, iuv, 0).x, texelFetch(noisetex, ivec2(255 - iuv.x, iuv.y), 0).x, texelFetch(noisetex, ivec2(iuv.x, 255 - iuv.y), 0).x);
}

    // ============================================================
//  CinematicVanilla V3 - tonemap.glsl
//  Reinhard-Jodie Extended + cinematic film grade.
//  V3 improvements:
//   - Seasonal color presets (Summer/Autumn/Winter/Spring/None)
//   - Poster Mode: aggressive grade for screenshots
//   - Improved split-tone with stronger teal-orange separation
//   - Film halation on bright highlights
// ============================================================

const float oneMinusShoulder         = 1.0 - SHOULDER_STRENGTH;
const float shoulderFactor           = oneMinusShoulder * 3.0;
const float shoulderWhitePointFactor = oneMinusShoulder / (WHITE_POINT * WHITE_POINT);

float getLuminance(in vec3 col){
    return dot(col, vec3(0.2126, 0.7152, 0.0722));
}

vec3 saturation(in vec3 col, in float a){
    float luma = getLuminance(col);
    return (col - luma) * a + luma;
}

vec3 contrast(in vec3 col, in float a){
    return (col - 0.5) * a + 0.5;
}

// Reinhard Extended Luminance
vec3 modifiedReinhardExtended(in vec3 color){
    float s = sumOf(color);
    return color * ((3.0 + s * shoulderWhitePointFactor) / (shoulderFactor + s));
}

// Reinhard Jodie Extended (per-channel + luminance blend)
vec3 modifiedReinhardJodieExtended(in vec3 color){
    float s = sumOf(color);
    vec3 rC = color * ((1.0 + color * shoulderWhitePointFactor) / (oneMinusShoulder + color));
    vec3 rL = color * ((3.0 + s * shoulderWhitePointFactor) / (shoulderFactor + s));
    return (rC - rL) * rC + rL;
}

// ─── Seasonal Grade ──────────────────────────────────────────────────────────
// Returns an additive tint + saturation multiplier for each season.
// SEASONAL_PRESET: 0=None 1=Summer 2=Autumn 3=Winter 4=Spring
vec3 seasonalGrade(in vec3 col){
    float luma = getLuminance(col);

    #if SEASONAL_PRESET == 1
        // Summer — warm golden, high contrast, lush greens
        col *= vec3(1.025, 1.010, 0.975);
        col  = saturation(col, 1.10);
        col  = contrast(col, 1.06);

    #elif SEASONAL_PRESET == 2
        // Autumn — amber shadows, desaturated sky, warm overall
        float shadowW = saturate(1.0 - luma * 2.5);
        col += vec3(0.030,  0.012, -0.018) * shadowW;   // amber shadow push
        col *= vec3(1.030, 1.012, 0.970);                // warm temp shift
        col  = saturation(col, 0.92);

    #elif SEASONAL_PRESET == 3
        // Winter — cold blue-white, desaturated, faint cyan shadows
        float shadowW = saturate(1.0 - luma * 2.5);
        col += vec3(-0.014, -0.004, 0.024) * shadowW;   // cold shadow push
        col *= vec3(0.975, 0.988, 1.028);                // cool temp shift
        col  = saturation(col, 0.82);
        col  = contrast(col, 1.08);

    #elif SEASONAL_PRESET == 4
        // Spring — soft pastel, bright, lifted shadows, green-pink bias
        col  = max(col, vec3(0.022));                    // lifted blacks
        col *= vec3(0.998, 1.015, 0.990);                // subtle green push
        col  = saturation(col, 0.96);
        col  = contrast(col, 0.97);

    #endif

    return col;
}

// ─── Cinematic Film Grade ────────────────────────────────────────────────────
// Applied in sRGB space after tonemapping. Pure math, zero texture reads.
vec3 cinematicGrade(in vec3 col){
    float luma = getLuminance(col);

    // 1. Shadow lift — prevents pure black, gives film-print look
    col = max(col, vec3(0.018));

    // 2. Split-tone: Shadows=teal-blue, Highlights=warm amber
    float shadowW    = saturate(1.0 - luma * 2.8);
    float highlightW = saturate(luma * 2.0 - 0.60);

    col += vec3(-0.012, -0.004, 0.018) * shadowW;
    col += vec3( 0.018,  0.010, -0.008) * highlightW;

    // 3. Midtone warmth (slight amber temperature)
    col *= vec3(1.015, 1.006, 0.988);

    // 4. Subtle midtone desaturation — analog film character
    float midW = saturate(1.0 - abs(luma * 2.0 - 1.0));
    col = mix(col, saturation(col, 0.88), midW * 0.3);

    // 5. Film halation — bright highlights bleed warm red/orange
    //    Simulates light scattering in film emulsion backing layer
    float halationW = saturate(luma - 0.72) * 2.0;
    col += vec3(0.060, 0.018, 0.006) * halationW * halationW;

    // 6. Seasonal grade on top
    col = seasonalGrade(col);

    return col;
}

// ─── Poster Mode Grade ───────────────────────────────────────────────────────
// Aggressive version of cinematicGrade for POSTER_MODE screenshots.
// Stronger teal-orange, crushed blacks, boosted contrast & saturation.
vec3 posterGrade(in vec3 col){
    float luma = getLuminance(col);

    // Deep shadow crush (cinematic blacks)
    col = pow(col, vec3(1.08));

    // Strong teal-orange split tone
    float shadowW    = saturate(1.0 - luma * 2.2);
    float highlightW = saturate(luma * 1.8 - 0.50);

    col += vec3(-0.022, -0.008, 0.032) * shadowW;
    col += vec3( 0.030,  0.016, -0.018) * highlightW;

    // Warm temperature push
    col *= vec3(1.022, 1.010, 0.976);

    // Film halation — stronger in poster mode
    float halationW = saturate(luma - 0.68) * 2.5;
    col += vec3(0.090, 0.028, 0.008) * halationW * halationW;

    // Boost contrast and saturation for that "epic screenshot" look
    col = contrast(col, 1.14);
    col = saturation(col, 1.18);

    // Seasonal grade still applies in poster mode
    col = seasonalGrade(col);

    return col;
}
    // ============================================================
//  CinematicVanilla V2 - dynamicLighting.glsl   (NEW)
//  Day/night light color transitions + soft GI approximation.
//  Include in complexShadingDeferred.glsl or world.glsl.
// ============================================================

// ─── Dynamic Light Color by Time of Day ─────────────────────────────────────
// Returns the sun/moon light color tinted for cinematic looks:
//   Dawn/Dusk  → warm amber-orange
//   Midday     → cool white-blue
//   Night      → cool blue-violet moonlight
vec3 getDynamicLightColor(in vec3 sunCol, in vec3 moonCol){
    #ifndef FORCE_DISABLE_DAY_CYCLE
        // dayCycleAdjust: 0=night, ~0.5=twilight, 1=midday
        float t  = dayCycleAdjust;
        float tw = 1.0 - abs(t * 2.0 - 1.0);  // peaks at 0.5 (twilight)
        tw *= tw;

        // Sunrise/sunset warm push — amber tint on sun light
        vec3 warmTwilightSun = sunCol * vec3(1.25, 0.90, 0.60);
        // Midday: slight cool-white push (high atmosphere scattering)
        vec3 middaySun       = sunCol * vec3(0.95, 0.98, 1.08);
        // Blend based on twilight factor
        vec3 dynSun = mix(middaySun, warmTwilightSun, tw);

        // Night: blue-violet moonlight
        vec3 dynMoon = moonCol * vec3(0.75, 0.82, 1.15);

        return mix(dynMoon, dynSun, t);
    #else
        return sunCol;
    #endif
}

// ─── Soft GI Approximation ──────────────────────────────────────────────────
// Very cheap: adds a small amount of sky color as a bounced indirect
// contribution scaled by the surface's upward normal component and lightmap.
// Mimics light bouncing off the ground/sky into shaded surfaces.
// normal: world-space surface normal
// skyCol: current sky color (linear)
// lightmapSky: the Y component of the lightmap (0..1)
vec3 getSoftGI(in vec3 normal, in vec3 skyCol, in float lightmapSky){
    // Upward-facing surfaces receive sky GI
    float upFacing = saturate(normal.y * 0.5 + 0.5);
    // Downward-facing surfaces get a faint ground bounce (brown-grey)
    float downFacing = saturate(-normal.y * 0.5 + 0.5);
    const vec3 groundBounce = vec3(0.12, 0.10, 0.07);

    vec3 gi = skyCol * upFacing * lightmapSky * 0.08
            + groundBounce * downFacing * lightmapSky * 0.04;
    return gi;
}

    void main(){
        // Screen texel coordinates
        ivec2 screenTexelCoord = ivec2(gl_FragCoord.xy);

        // Get scene color
        postColOut = texelFetch(colortex4, screenTexelCoord, 0).rgb;

        #ifdef BLOOM
            // Uncompress the HDR colors and upscale
            vec3 bloomCol = getBloomTile(vec2(0), 0.25);
            bloomCol += getBloomTile(vec2(0, 0.2578125), 0.125);
            bloomCol += getBloomTile(vec2(0.12890625, 0.2578125), 0.0625);
            bloomCol += getBloomTile(vec2(0.1953125, 0.2578125), 0.03125);
            bloomCol += getBloomTile(vec2(0.12890625, 0.328125), 0.015625);

            // Average the total samples (1 / 5 bloom tiles multiplied by 1 / 4 samples used for the box blur)
            bloomCol *= 0.05;

            float bloomLuma = sumOf(bloomCol);
            // Apply bloom by tonemapped luma and BLOOM_STRENGTH
            postColOut += (bloomCol - postColOut) * ((BLOOM_STRENGTH * bloomLuma) / (3.0 + bloomLuma));
        #endif

        #if defined LENS_FLARE && defined WORLD_LIGHT
            #ifdef DISTANT_HORIZONS
                bool isSky = textureLod(dhDepthTex1, shdLightDirScreenSpace.xy, 0).x == 1 && textureLod(depthtex0, shdLightDirScreenSpace.xy, 0).x == 1;
            #else
                bool isSky = textureLod(depthtex0, shdLightDirScreenSpace.xy, 0).x == 1;
            #endif

            #ifdef FORCE_DISABLE_WEATHER
                if(isSky) postColOut += getLensFlare(texCoord - 0.5, shdLightDirScreenSpace.xy - 0.5) * (1.0 - blindness) * (1.0 - darknessFactor);
            #else
                if(isSky) postColOut += getLensFlare(texCoord - 0.5, shdLightDirScreenSpace.xy - 0.5) * (1.0 - blindness) * (1.0 - darknessFactor) * (1.0 - rainStrength);
            #endif
        #endif

        #ifdef AUTO_EXPOSURE
            // Get center pixel current average scene luminance and mix previous and current pixel...
            float centerPixLuminance = sumOf(textureLod(colortex4, vec2(0.5), 8).rgb);

            // Accumulate current luminance
            float frameTimeExposure = AUTO_EXPOSURE_SPEED * frameTime;
            float tempPixLuminance = mix(texelFetch(colortex5, ivec2(1), 0).a, centerPixLuminance, frameTimeExposure / (1.0 + frameTimeExposure));

            // Apply auto exposure by dividing it by the pixel's luminance in sRGB
            const float invMinimumExposure = 1.0 / MINIMUM_EXPOSURE;
            postColOut *= min(inversesqrt(tempPixLuminance), invMinimumExposure);

            #if (defined PREVIOUS_FRAME && (defined SSR || defined SSGI)) || ANTI_ALIASING >= 2
                temporalDataOut = vec4(texelFetch(colortex5, screenTexelCoord, 0).rgb, tempPixLuminance);
            #else
                temporalDataOut = vec4(0, 0, 0, tempPixLuminance);
            #endif
        #endif

        #ifdef VIGNETTE
            postColOut *= max(0.0, 1.0 - lengthSquared(texCoord - 0.5) * VIGNETTE_STRENGTH);
        #endif

        // Color tinting, exposure, and tonemapping
        const vec3 exposureTint = vec3(TINT_R, TINT_G, TINT_B) * (EXPOSURE * 0.00392156863);
        postColOut = modifiedReinhardExtended(postColOut * exposureTint);

        // Gamma correction
        postColOut = toSRGB(postColOut);

        // --- CinematicVanilla V3: filmic grade / poster mode ---
        #ifdef POSTER_MODE
            postColOut = posterGrade(postColOut);
        #else
            postColOut = cinematicGrade(postColOut);
        #endif

        // Contrast and saturation
        postColOut = contrast(postColOut, CONTRAST);
        postColOut = saturation(postColOut, SATURATION);

        // Apply dithering to break postColOut banding
        postColOut += (texelFetch(noisetex, screenTexelCoord & 255, 0).x - 0.5) * 0.00392156863;
    }
#endif