#version 410 core
// Generated by irisbridge from a shaderpack source. Do not edit.
#define MC_VERSION 12100
#define MC_GL_VERSION 460
#define MC_GLSL_VERSION 460
#define MC_MIPMAP_LEVEL 4
#define MC_RENDER_QUALITY 1.0
#define MC_SHADOW_QUALITY 1.0
#define MC_HAND_DEPTH 0.125
#define MC_NORMAL_MAP
#define MC_SPECULAR_MAP
#define MAX_COLOR_BUFFERS 16
#define IS_IRIS
#define IRIS_TAG_SUPPORT 2
#define IRIS_VERSION 10800
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUNSET 2
#define MC_RENDER_STAGE_CUSTOM_SKY 3
#define MC_RENDER_STAGE_SUN 4
#define MC_RENDER_STAGE_MOON 5
#define MC_RENDER_STAGE_STARS 6
#define MC_RENDER_STAGE_VOID 7
#define MC_RENDER_STAGE_TERRAIN_SOLID 8
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 9
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 10
#define MC_RENDER_STAGE_ENTITIES 11
#define MC_RENDER_STAGE_BLOCK_ENTITIES 12
#define MC_RENDER_STAGE_DESTROY 13
#define MC_RENDER_STAGE_OUTLINE 14
#define MC_RENDER_STAGE_DEBUG 15
#define MC_RENDER_STAGE_HAND_SOLID 16
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 17
#define MC_RENDER_STAGE_TRIPWIRE 18
#define MC_RENDER_STAGE_PARTICLES 19
#define MC_RENDER_STAGE_CLOUDS 20
#define MC_RENDER_STAGE_RAIN_SNOW 21
#define MC_RENDER_STAGE_WORLD_BORDER 22
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 23
#define MC_OS_LINUX
#define MC_GL_VENDOR_INTEL
#define MC_GL_RENDERER_INTEL

// ---- Cubyz compatibility shim ----
uniform mat3 cubyz_NormalMatrix;

// ---- shaderpack source ----

/*
const int colortex0Format = RGB16F;
*/
/*
const int colortex1Format = RGB16F;
*/
/*
const int colortex2Format = RGB16F;
*/
/*
const int colortex5Format = RGB16F;
*/
/*
const int colortex7Format = RGB16F;
*/

#define SHADOW_ENABLED 0 // [0 1]
#define SHADOW_RESOLUTION 4608 // [512 1024 1536 2048 2560 3072 3584 4096 4608 8128]
#define SHADOW_QUALITY 2 // [1 2 3 4 5 6 7 8]
#define SHADOW_SOFTNESS 2 // [2 3 4 5 6 7 8]
#define SHADOW_NOISERESOLUTION 3584 // [8 216 512 1024 1536 2048 2560 3072 3584 4096 4608 8128]
//
#define SUN_PATHROTATION 40 // [-50 -45 -40 -35 -30 -25 -20 -15 -10 -5 0 5 10 15 20 25 30 35 40 45 50]
//
#define GODRAYS_ENABLED 0 // [0 1]
#define GODRAYS_SAMPLES 36 // [12 24 36]
#define GODRAYS_EXPOSURE 0.41 // [0.25 0.35 0.41 0.5 0.75 1.0]
#define GODRAYS_DECAY 0.88 // [0.80 0.85 0.88 0.91 0.95 1.0]
#define GODRAYS_DENSITY 1.25 // [0.5 0.75 1.0 1.25 1.5 2.0]
#define GODRAYS_WEIGHT 1.15 // [0.5 0.75 1.0 1.15 1.25 1.5]
//
#define TONEMAP_ENABLED 1 // [0 1]
#define TONEMAPPING 0 // [0 1]
//
#define MOTION_BLUR_ENABLED 1 // [0 1]
#define MB_MAX_BLUR_AMOUNT 1.0 // [0.5 1.0 1.5] 
#define MB_BLUR_SAMPLES 64 // [4 8 16 24 32 48 64]
#define MB_EDGE_THRESHOLD 1.0 // [0.25 0.5 0.75 1.0]
#define MB_COLOR_INTENSITY 1.0 // [0.5 0.75 1.0 1.25 1.5]
#define MB_DEPTH_THRESHOLD 0.66
//
#define FULLBRIGHT 0 // [0 1]
//
#define BLOOM_ENABLED 0 // [0 1]
#define BLOOM_RADIUS 5.0 // [2.0 2.5 3.0 3.5 4.0 4.5 5.0 5.5]
#define BLOOM_THRESHOLD 0.87 // [0.25 0.5 0.75 0.87 1]
//
#define SUN_ILLUMINANCE 1 
#define MOON_ILLUMINANCE 1
//
#define SELECT_RED 0
#define SELECT_GREEN 0 
#define SELECT_BLUE 0
//
#define WATER_WAVE_HEIGHT 0.25 // [0.1 0.25 0.5 1.0]
#define WATER_WAVE_SPEED 0.05 // [0.01 0.05 0.1 0.2]
//
#define SKY_FIX 0 // [0 1]
//
#define SSR 0 // [0 1]

const bool shadowtex0Nearest = true;
const bool shadowtex1Nearest = true;
const bool shadowcolor0Nearest = true;

const float sunPathRotation = SUN_PATHROTATION;
const int noiseTextureResolution = SHADOW_NOISERESOLUTION;
const int shadowMapResolution = SHADOW_RESOLUTION;

vec3 lightmap_blocklightColor = vec3(0.85, 0.42, 0.12);
vec3 lightmap_skylightColor = vec3(0.10, 0.15, 0.22);
vec3 lightmap_sunlightColor = vec3(0.85, 0.92, 1.0);
vec3 lightmap_morningSunlightColor = vec3(0.80, 0.55, 0.35);
vec3 lightmap_moonlightColor = vec3(0.45, 0.55, 1.0);  
vec3 lightmap_nightSkyColor = vec3(0.06, 0.12, 0.45);
vec3 lightmap_morningSkyColor = vec3(0.65, 0.55, 0.38);
vec3 lightmap_ambientColor = vec3(0.08, 0.08, 0.08);
vec3 lightmap_nightBlockColor = vec3(0.10, 0.09, 0.07);
vec3 lightmap_nightAmbientColor = vec3(0.06, 0.06, 0.06);
vec3 lightmap_duskSunlightColor = vec3(0.85, 0.40, 0.35);
vec3 lightmap_duskSkyColor = vec3(0.75, 0.45, 0.38);

vec3 sky_earlySkyColor = vec3(0.1, 0.05, 0.02);
vec3 sky_daySkyColor = vec3(0.2, 0.35, 0.5);
vec3 sky_duskSkyColor = vec3(0.1, 0.05, 0.02);
vec3 sky_nightSkyColor = vec3(0.01, 0.01, 0.03);

vec3 earlyGodrayColor = vec3(1.0, 0.2353, 0.0627);
vec3 duskGodrayColor = vec3(1.0, 0.0667, 0.0);
vec3 godrayColor = vec3(0.9882, 0.6824, 0.4314);
vec3 moonrayColor = vec3(0.1608, 0.2941, 0.9608);
vec3 rainGodrayColor = vec3(0.5882, 0.5882, 0.5882);
vec3 waterTint = vec3(0.0, 0.0667, 1.0);
uniform sampler2D colortex0;
uniform sampler2D colortex1;
uniform sampler2D colortex2;
uniform sampler2D colortex3;
uniform sampler2D colortex5;
uniform sampler2D colortex6;
uniform sampler2D colortex7;
uniform sampler2D colortexN;

uniform sampler2D depthtex0;
uniform sampler2D depthtex1;

uniform sampler2D shadowtex0;
uniform sampler2D shadowtex1;

uniform sampler2D gaux1;
uniform sampler2D gaux2;

uniform sampler2D shadowcolor0;

uniform int renderStage;

uniform sampler2D noisetex;

uniform float viewWidth;
uniform float viewHeight;

uniform mat4 gbufferModelViewInverse;
uniform mat4 gbufferModelView;
uniform mat4 gbufferProjectionInverse;
uniform mat4 gbufferProjection;
uniform mat4 shadowModelView;
uniform mat4 shadowProjection;
uniform mat4 modelViewMatrix;
uniform mat4 projectionMatrix;
uniform vec3 cameraPosition, previousCameraPosition;
uniform mat4 gbufferPreviousProjection;
uniform mat4 gbufferPreviousModelView;
uniform mat4 gbufferPreviousModelViewInverse;

uniform int blockEntityId;

uniform int frameCounter;
uniform int frameTime;
uniform int frameTimeCounter;

uniform sampler2D gtexture;

uniform sampler2D lightmap;

uniform vec3 shadowLightPosition;

uniform int isEyeInWater;

uniform int worldTime;

uniform float weight[5] = float[] (0.227027, 0.1945946, 0.1216216, 0.054054, 0.016216);
uniform bool horizontal;
vec4 fsh_basic_color(vec2 TexCoord)
{
  return texture(colortex0, TexCoord);
}

vec4 fsh_basic_gtexture(vec2 TexCoord, vec4 Color)
{
  vec4 color = texture(gtexture, TexCoord) * Color;
  if (color.a < 0.1)
  {
    discard;
  }
  return color;
}
vec2 vsh_correct_lightmap(vec2 lightmap)
{
  return (lightmap * 33.05 / 32.0) - (1.05 / 32.0);
}

vec4 fsh_lightmapData(vec2 lightmapCoord)
{
  return vec4(lightmapCoord, 0.0, 1.0);
}

vec2 fsh_getLightmap(vec2 texcoord)
{
  return texture(colortex1, texcoord).rg;
}

vec3 fsh_apply_lightColors(vec2 lightmap, vec3 normal, vec3 shadow)
{  
    vec3 lightVector = normalize(shadowLightPosition);
    vec3 worldLightVector = mat3(gbufferModelViewInverse) * lightVector;
    
    vec3 blocklight = lightmap.r * lightmap_blocklightColor * 1.5;
    vec3 skylight = lightmap.g * lightmap_skylightColor;
    vec3 ambient = lightmap_ambientColor;
    
    float sunDot = clamp(dot(worldLightVector, normal), 0.0, 1.0);
    vec3 sunlight = lightmap_sunlightColor * sunDot * lightmap.g * shadow;
    
    if (worldTime >= 0 && worldTime < 1000)
    {
        float time = smoothstep(0, 1000, float(worldTime));
        sunlight = mix(lightmap_morningSunlightColor, sunlight, time) * sunDot * shadow;
        skylight = mix(lightmap_morningSkyColor / 18, lightmap_skylightColor, time) * lightmap.g;
    } 
    else if (worldTime >= 1000 && worldTime < 11500)
    {
        float time = smoothstep(10000, 11500, float(worldTime));
        sunlight = mix(lightmap_sunlightColor, lightmap_duskSunlightColor, time) * sunDot * shadow;
        skylight = mix(lightmap_skylightColor, lightmap_duskSkyColor / 18, time) * lightmap.g;
    } 
    else if (worldTime >= 11500 && worldTime < 13000)
    {
        float time = smoothstep(11500, 13000, float(worldTime));
        sunlight = mix(lightmap_duskSunlightColor, lightmap_moonlightColor / 12, time) * sunDot * shadow;
        skylight = mix(lightmap_duskSkyColor / 18, lightmap_nightSkyColor / 14, time) * lightmap.g;
        ambient = mix(lightmap_ambientColor, lightmap_nightAmbientColor / 8, time);
    } 
    else if (worldTime >= 13000 && worldTime < 24000)
    {
        float time = smoothstep(23215, 24000, float(worldTime));
        sunlight = mix(lightmap_moonlightColor / 17, lightmap_morningSunlightColor, time) * sunDot * shadow;
        skylight = mix(lightmap_nightSkyColor / 18, lightmap_morningSkyColor / 18, time) * lightmap.g;
        ambient = mix(lightmap_nightAmbientColor / 8, lightmap_ambientColor / 4, time);
    }

    return blocklight + skylight + ambient + sunlight;
}
vec3 vsh_get_normal()
{
  return cubyz_NormalMatrix * cubyz_Normal;
}

vec3 vsh_convert_normal_to_worldplayer(vec3 normal)
{
  return mat3(gbufferModelViewInverse) * normal;
}

vec4 fsh_encodedNormal(vec3 normal)
{
  return vec4(normal * 0.5 + 0.5, 1.0);
}

vec3 fsh_get_normalized(vec2 texcoord)
{
  vec3 encodedNormal = texture(colortex2, texcoord).rgb;
  return normalize((encodedNormal - 0.5) * 2.0);
}
float fsh_get_depth(vec2 texcoord)
{
  return texture(depthtex0, texcoord).r;
}
//Interleaved Gradient Noise Calculations
float IGN(vec2 coord)
{
    return fract(52.9829189f * fract(0.06711056f * coord.x + 0.00583715f* coord.y));
}

float IGN(vec2 coord, int frame)
{
    return  IGN(coord + 5.588238 * (frame & 63));
}

vec3 viewSpaceToScreenSpace(vec3 viewPosition) {
	vec3 screenPosition  = vec3(gbufferProjection[0].x, gbufferProjection[1].y, gbufferProjection[2].z) * viewPosition + gbufferProjection[3].xyz;
  screenPosition /= -viewPosition.z;

  return screenPosition * 0.5 + 0.5;
}
float viewSpaceToScreenSpace(float depth, mat4 projection) {
	return ((projection[2].z * depth + projection[3].z) / -depth) * 0.5 + 0.5;
}
vec3 doGodrays(vec3 color, vec2 texcoord)
{
  color = vec3(0);

  vec2 altCoord = texcoord;

  vec3 LightVector = viewSpaceToScreenSpace(shadowLightPosition);
  LightVector.xy = clamp(LightVector.xy, vec2(-0.5), vec2(1.5));

  vec2 deltaTexCoord = (texcoord - LightVector.xy);
  deltaTexCoord *= 1.0 / float(GODRAYS_SAMPLES) * GODRAYS_DENSITY;

  float illuminationDecay = 2.0;
  float weight = 0.23 * SUN_ILLUMINANCE;

  altCoord -= deltaTexCoord * IGN(floor(gl_FragCoord.xy), frameCounter);

  for (int i = 0; i < GODRAYS_SAMPLES; i++)
  {
    vec3 samples = vec3(0.0);

    if (texture(depthtex0, altCoord).r == 1.0)
    {
      if (worldTime < 1000) { 
        float t = smoothstep(500, 1000, float(worldTime));
        samples = mix(earlyGodrayColor, godrayColor, t);
      } 
      else if (worldTime < 12350)
      {
        float t = smoothstep(10000, 12350, float(worldTime));
        samples = mix(godrayColor, duskGodrayColor, t);
      } 
      else if (worldTime < 23500) 
      {
        float t = smoothstep(12350, 13000, float(worldTime));
        samples = mix(earlyGodrayColor, moonrayColor, t);
        weight = 0.14 * MOON_ILLUMINANCE;
      }
    }

    if (isEyeInWater == 1)
    {
      if (texture(depthtex1, altCoord).r == 1.0)
      {
        samples = mix(vec3(0.0941, 0.0392, 0.8275), godrayColor, waterTint);
      }
      weight = 0.3;
      samples *= 1.2; // This was your exposure tweak under water
    }

    samples *= illuminationDecay * weight;
    color += samples;
    illuminationDecay *= GODRAYS_DECAY;
    altCoord -= deltaTexCoord;
  }

  color /= GODRAYS_SAMPLES;
  color *= GODRAYS_EXPOSURE;

  return color;
}

in vec2 TexCoord;

/* RENDERTARGETS: 0,7 */
layout(location = 0) out vec4 Color;
layout(location = 1) out vec3 color;

void main()
{
  Color = fsh_basic_color(TexCoord);

  float depth = fsh_get_depth(TexCoord);

  #if GODRAYS_ENABLED == 1
    color = doGodrays(color, TexCoord);
  #endif
}
