#version 410 core
// Generated by irisbridge from a shaderpack source. Do not edit.
	extension GL_ARB_explicit_attrib_location : enable
#define MC_VERSION 12100
#define MC_GL_VERSION 460
#define MC_GLSL_VERSION 460
#define MC_MIPMAP_LEVEL 4
#define MC_RENDER_QUALITY 1.0
#define MC_SHADOW_QUALITY 1.0
#define MC_HAND_DEPTH 0.125
#define MC_NORMAL_MAP
#define MC_SPECULAR_MAP
#define MAX_COLOR_BUFFERS 16
#define IS_IRIS
#define IRIS_TAG_SUPPORT 2
#define IRIS_VERSION 10800
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUNSET 2
#define MC_RENDER_STAGE_CUSTOM_SKY 3
#define MC_RENDER_STAGE_SUN 4
#define MC_RENDER_STAGE_MOON 5
#define MC_RENDER_STAGE_STARS 6
#define MC_RENDER_STAGE_VOID 7
#define MC_RENDER_STAGE_TERRAIN_SOLID 8
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 9
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 10
#define MC_RENDER_STAGE_ENTITIES 11
#define MC_RENDER_STAGE_BLOCK_ENTITIES 12
#define MC_RENDER_STAGE_DESTROY 13
#define MC_RENDER_STAGE_OUTLINE 14
#define MC_RENDER_STAGE_DEBUG 15
#define MC_RENDER_STAGE_HAND_SOLID 16
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 17
#define MC_RENDER_STAGE_TRIPWIRE 18
#define MC_RENDER_STAGE_PARTICLES 19
#define MC_RENDER_STAGE_CLOUDS 20
#define MC_RENDER_STAGE_RAIN_SNOW 21
#define MC_RENDER_STAGE_WORLD_BORDER 22
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 23
#define MC_OS_LINUX
#define MC_GL_VENDOR_INTEL
#define MC_GL_RENDERER_INTEL

// ---- Cubyz compatibility shim ----

// ---- shaderpack source ----

#define FINAL_VSH 1

#if !defined FINAL_GLSL_INCLUDED
#define FINAL_GLSL_INCLUDED

#if defined FINAL_FSH
#
	uniform sampler2D colortex0;

	in vec2 uv;

	/* DRAWBUFFERS:0 */
	layout(location = 0) out vec4 fragData0;

	void main() {
	vec3 albedo = texture(colortex0, uv).rgb;

		/* colortex0 (gcolor) */
		fragData0 = vec4(albedo, 1.0);
	}
#endif /* defined FINAL_FSH */

#if defined FINAL_VSH
	uniform mat4 modelViewMatrix;
	uniform mat4 projectionMatrix;

	in vec2 vaUV0;
	in vec3 vaPosition;

	out vec2 uv;

	void main() {
	uv = vaUV0;
		gl_Position = projectionMatrix * (modelViewMatrix * vec4(vaPosition, 1.0));
	}
#endif /* defined FINAL_VSH */

#endif /* !defined FINAL_GLSL_INCLUDED */