#version 410 core
// Generated by irisbridge from a shaderpack source. Do not edit.
#define MC_VERSION 12100
#define MC_GL_VERSION 460
#define MC_GLSL_VERSION 460
#define MC_MIPMAP_LEVEL 4
#define MC_RENDER_QUALITY 1.0
#define MC_SHADOW_QUALITY 1.0
#define MC_HAND_DEPTH 0.125
#define MC_NORMAL_MAP
#define MC_SPECULAR_MAP
#define MAX_COLOR_BUFFERS 16
#define IS_IRIS
#define IRIS_TAG_SUPPORT 2
#define IRIS_VERSION 10800
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUNSET 2
#define MC_RENDER_STAGE_CUSTOM_SKY 3
#define MC_RENDER_STAGE_SUN 4
#define MC_RENDER_STAGE_MOON 5
#define MC_RENDER_STAGE_STARS 6
#define MC_RENDER_STAGE_VOID 7
#define MC_RENDER_STAGE_TERRAIN_SOLID 8
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 9
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 10
#define MC_RENDER_STAGE_ENTITIES 11
#define MC_RENDER_STAGE_BLOCK_ENTITIES 12
#define MC_RENDER_STAGE_DESTROY 13
#define MC_RENDER_STAGE_OUTLINE 14
#define MC_RENDER_STAGE_DEBUG 15
#define MC_RENDER_STAGE_HAND_SOLID 16
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 17
#define MC_RENDER_STAGE_TRIPWIRE 18
#define MC_RENDER_STAGE_PARTICLES 19
#define MC_RENDER_STAGE_CLOUDS 20
#define MC_RENDER_STAGE_RAIN_SNOW 21
#define MC_RENDER_STAGE_WORLD_BORDER 22
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 23
#define MC_OS_LINUX
#define MC_GL_VENDOR_INTEL
#define MC_GL_RENDERER_INTEL

// ---- Cubyz compatibility shim ----
layout(location = 0) out vec4 cubyz_FragData[1];
vec4 cubyz_texture2D(sampler2D s, vec2 c) {return texture(s, c);}
vec4 cubyz_texture2D(sampler2D s, vec2 c, float b) {return texture(s, c, b);}

// ---- shaderpack source ----

// Input data from vertex shader
in vec2 vTexCoord;
in vec4 vPosition;

// Textures
uniform sampler2D gtexture;
uniform sampler2D tex;

// Parameters for post-processing
uniform float time;

uniform sampler2D shadowtex0;
in vec4 shadowPos;



void main()
{
    vec4 color = cubyz_texture2D(gtexture, vTexCoord);


    // black-gold color palette
    float gray = dot(color.rgb, vec3(0.3, 0.59, 0.11));
    vec3 sepia = vec3(1.2 * gray, 1.0 * gray, 0.8 * gray);
    

    // granularity (noise effect)
    float noise = fract(sin(dot(vTexCoord.xy + time, vec2(12.9898, 78.233))) * 43758.5453) * NOISE;
    sepia += noise * 0.1;


    // smooth shadows
    vec4 shadowColor = vec4(0.2, 0.2, 0.4, 1.0); // Blue shadow
    float shadowFactor = 0.1;
    sepia = mix(sepia, shadowColor.rgb, shadowFactor);


    // **Chromatic Aberration & Double Vision Effect**
    float distortion = sin(vTexCoord.y * 10.0 + time * 2.0) * GLICH; // Ripped distortion //0.01
    vec2 offsetR = vec2(distortion, 0.0);
    vec2 offsetB = vec2(-distortion, 0.0);

    float r = cubyz_texture2D(gtexture, vTexCoord + offsetR).r;
    float g = cubyz_texture2D(gtexture, vTexCoord).g;
    float b = cubyz_texture2D(gtexture, vTexCoord + offsetB).b;

    vec3 chromaticColor = vec3(r, g, b);


    // **Ghost Image (double vision)**
    vec4 ghost = cubyz_texture2D(gtexture, vTexCoord + vec2(distortion * 2.0, distortion * GIMG));
    chromaticColor = mix(chromaticColor, ghost.rgb, 0.3);

    chromaticColor += noise;


    // Calculation of bloom effect
    vec4 bloom = vec4(0.0);
    vec4 blurColor = vec4(-0.0); //brg
    float intensity = -2.0; //color-
    float radius = 0.1;
    for(int i = -4; i < 4; i++) {
        for(int j = -4; j < 4; j++) {
            vec2 offset = vec2(float(i), float(j)) / 312.0;
            blurColor += cubyz_texture2D(gtexture, vTexCoord + offset) * BLURCOLOR; //0.006
        }
    }
    bloom = blurColor * intensity;


    // Applying bloom to the main color
    chromaticColor += bloom.rgb;

    vec3 finalColor = mix(sepia, chromaticColor, 0.51);

    cubyz_FragData[0] = vec4(finalColor, color.a);
}