#version 460 core
// Generated by irisbridge from a shaderpack source. Do not edit.
	extension GL_ARB_explicit_attrib_location : enable
#define MC_VERSION 12100
#define MC_GL_VERSION 460
#define MC_GLSL_VERSION 460
#define MC_MIPMAP_LEVEL 4
#define MC_RENDER_QUALITY 1.0
#define MC_SHADOW_QUALITY 1.0
#define MC_HAND_DEPTH 0.125
#define MC_NORMAL_MAP
#define MC_SPECULAR_MAP
#define MAX_COLOR_BUFFERS 16
#define IS_IRIS
#define IRIS_TAG_SUPPORT 2
#define IRIS_VERSION 10800
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUNSET 2
#define MC_RENDER_STAGE_CUSTOM_SKY 3
#define MC_RENDER_STAGE_SUN 4
#define MC_RENDER_STAGE_MOON 5
#define MC_RENDER_STAGE_STARS 6
#define MC_RENDER_STAGE_VOID 7
#define MC_RENDER_STAGE_TERRAIN_SOLID 8
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 9
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 10
#define MC_RENDER_STAGE_ENTITIES 11
#define MC_RENDER_STAGE_BLOCK_ENTITIES 12
#define MC_RENDER_STAGE_DESTROY 13
#define MC_RENDER_STAGE_OUTLINE 14
#define MC_RENDER_STAGE_DEBUG 15
#define MC_RENDER_STAGE_HAND_SOLID 16
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 17
#define MC_RENDER_STAGE_TRIPWIRE 18
#define MC_RENDER_STAGE_PARTICLES 19
#define MC_RENDER_STAGE_CLOUDS 20
#define MC_RENDER_STAGE_RAIN_SNOW 21
#define MC_RENDER_STAGE_WORLD_BORDER 22
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 23
#define MC_OS_LINUX
#define MC_GL_VENDOR_INTEL
#define MC_GL_RENDERER_INTEL

// ---- Cubyz compatibility shim ----

// ---- Cubyz vertex prologue ----
uniform mat4 cubyz_skyProjectionInverse;
uniform mat4 cubyz_skyModelViewInverse;

// ---- the Minecraft vertex environment, computed rather than attributed ----
vec4 cubyz_Vertex;
vec3 cubyz_Normal;
vec4 cubyz_Color;
vec4 cubyz_MultiTexCoord0;
vec4 cubyz_MultiTexCoord1;
vec3 mc_Entity;
vec4 mc_midTexCoord;
vec4 at_tangent;
vec3 at_midBlock;

void cubyz_setupVertex() {
    // The standard three-vertex fullscreen triangle: (-1,-1), (3,-1), (-1,3).
    vec2 ndc = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2))*2.0 - 1.0;

    // Unproject the far plane. Dividing by w before the second transform keeps the point
    // finite; the pack's `ftransform` re-applies the same pair, so the clip position it
    // computes differs from `ndc` only by a positive scale, which the perspective divide
    // removes.
    vec4 view = cubyz_skyProjectionInverse*vec4(ndc, 1.0, 1.0);
    view /= view.w;
    vec4 world = cubyz_skyModelViewInverse*view;

    cubyz_Vertex = vec4(world.xyz, 1.0);

    // Vanilla sky geometry carries a white vertex colour. Packs lean on that: Complementary
    // detects vanilla *stars* with `glColor.r == glColor.g && glColor.r < 0.51` and discards
    // when it matches, so handing over anything grey and dim would erase the sky it is
    // being asked to draw.
    cubyz_Color = vec4(1.0);
    cubyz_Normal = vec3(0.0, 1.0, 0.0);
    cubyz_MultiTexCoord0 = vec4((ndc*0.5 + 0.5), 0.0, 1.0);
    // Full sky light, no block light - the sky is not lit by the world. Raw 0..240 like the
    // terrain prologue's; the lightmap matrix in gl_TextureMatrix[1] brings it to 31/32.
    cubyz_MultiTexCoord1 = vec4(0.0, 240.0, 0.0, 1.0);
    mc_midTexCoord = vec4(0.5, 0.5, 0.0, 0.0);
    at_tangent = vec4(1.0, 0.0, 0.0, 1.0);
    mc_Entity = vec4(0.0).xyz;
    at_midBlock = vec4(0.0).xyz;
}
void cubyz_packMain();

void main() {
    cubyz_setupVertex();
    cubyz_packMain();
}


// ---- shaderpack source ----

#define GBUFFERS_VSH 1
#define GBUFFERS_SKYBASIC 1

#if !defined GBUFFERS_GLSL_INCLUDED
#define GBUFFERS_GLSL_INCLUDED 1

#if defined GBUFFERS_WATER || defined GBUFFERS_HAND_WATER
#	define GBUFFERS_TRANSLUCENT 1
#endif

#if defined GBUFFERS_CLOUDS || defined GBUFFERS_SKYBASIC || defined GBUFFERS_SKYTEXTURED
#	define GBUFFERS_SKY 1
#endif

#if defined GBUFFERS_ARMOR_GLINT || defined GBUFFERS_BEACONBEAM || defined GBUFFERS_BLOCK || defined GBUFFERS_CLOUDS || defined GBUFFERS_ENTITIES || defined GBUFFERS_HAND_WATER || defined GBUFFERS_HAND || defined GBUFFERS_SKYTEXTURED || defined GBUFFERS_SPIDEREYES || defined GBUFFERS_TERRAIN || defined GBUFFERS_TEXTURED_LIT || defined GBUFFERS_TEXTURED || defined GBUFFERS_WATER || defined GBUFFERS_WEATHER
#	define USE_TEXTURES 1
#endif

#if defined GBUFFERS_BASIC || defined GBUFFERS_BLOCK || defined GBUFFERS_ENTITIES || GBUFFERS_HAND_WATER || defined GBUFFERS_HAND || defined GBUFFERS_TERRAIN || defined GBUFFERS_TEXTURED_LIT || defined GBUFFERS_TEXTURED || defined GBUFFERS_WATER || defined GBUFFERS_WEATHER
#   define USE_LIGHTMAP 1
#endif

#if defined GBUFFERS_TERRAIN || defined GBUFFERS_WATER
#	define USE_CHUNK_OFFSET 1
#endif

#if defined GBUFFERS_BASIC || defined GBUFFERS_BEACONBEAM || defined GBUFFERS_BLOCK || defined GBUFFERS_CLOUDS || defined GBUFFERS_ENTITIES || defined GBUFFERS_HAND_WATER || defined GBUFFERS_HAND || defined GBUFFERS_LINE || defined GBUFFERS_SPIDEREYES || defined GBUFFERS_TERRAIN || defined GBUFFERS_TEXTURED_LIT || defined GBUFFERS_TEXTURED || defined GBUFFERS_WATER || defined GBUFFERS_WEATHER
#	define USE_ALPHA_TEST 1
#endif

#if defined GBUFFERS_FSH
#
#	if defined USE_TEXTURES
		uniform sampler2D gtexture;
		uniform sampler2D normals;
		uniform sampler2D specular;
		uniform ivec2 atlasSize;
#	endif
#	if defined USE_LIGHTMAP
		uniform sampler2D lightmap;
#	endif
#	if defined GBUFFERS_BASIC
		uniform int renderStage;
#	endif
#	if defined USE_ALPHA_TEST
		uniform float alphaTestRef;
#	endif
#	if defined GBUFFERS_ENTITIES
		uniform vec4 entityColor;
#	endif
	uniform sampler2D depthtex0, depthtex1;
	uniform mat4 gbufferProjection, gbufferProjectionInverse;
	uniform mat4 gbufferModelView, gbufferModelViewInverse;
	uniform vec3 cameraPosition;
	uniform vec3 fogColor;
	uniform float fogStart, fogEnd;
	uniform float viewHeight, viewWidth;
	uniform int fogMode;

#	if defined USE_TEXTURES
		in vec2 uv0;
#	endif
#	if defined USE_LIGHTMAP
		in vec2 uv1;
#	endif
	in float mcEntity;
	in vec4 col;
	in vec4 viewPos;
	in vec4 relPos;
	in vec3 vNormal;
	in vec3 sunPos;
	in vec3 moonPos;
	in vec3 shadowLightPos;
	in mat3 tbnMatrix;

	/* DRAWBUFFERS:0123456 */
	layout(location = 0) out vec4 fragData0;
	layout(location = 1) out vec4 fragData1;
	layout(location = 2) out vec4 fragData2;
	layout(location = 3) out vec4 fragData3;
	layout(location = 4) out vec4 fragData4;
	layout(location = 5) out vec4 fragData5;
	layout(location = 6) out vec4 fragData6;

	float fresnelSchlick(const vec3 H, const vec3 N, const float reflectance) {
		float cosTheta = clamp(1.0 - max(0.0, dot(H, N)), 0.0, 1.0);

		return reflectance + (1.0 - reflectance) * cosTheta * cosTheta * cosTheta * cosTheta * cosTheta;
	}

	float getFog(const int fogMode, const float fogStart, const float fogEnd, const vec4 pos) {
		if (fogMode == 9729) { // GL_LINEAR
			return clamp((length(pos) - fogStart) / (fogEnd - fogStart), 0.0, 1.0);
		} else if (fogMode == 2048) { // GL_EXP
			return 1.0 - clamp(1.0 / exp(max(0.0, length(pos) - fogStart) * log(1.0 / 0.03) / (fogEnd - fogStart)), 0.0, 1.0);
		} else if (fogMode == 2049) { // GL_EXP2
			float base = max(0.0, length(pos) - fogStart) * sqrt(log(1.0 / 0.015)) / (fogEnd - fogStart);
			return 1.0 - clamp(1.0 / exp(base * base), 0.0, 1.0);
		} else {
			return 0.0;
		}
	}

	#if !defined REFLECTIVE_VANILLA_CONFIG_GLSL_INCLUDED
#define REFLECTIVE_VANILLA_CONFIG_GLSL_INCLUDED

#define SPECULAR 0
#define VANILLA 1

#define ENABLE_GAMMA_CORRECTION
#define ENABLE_TONEMAPPING
#define CONTRAST_FILTER_INTENSITY 1.16 // [0.00 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.30 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.40 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.50 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.60 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.70 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.80 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.90 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.00 1.01 1.02 1.03 1.04 1.05 1.06 1.07 1.08 1.09 1.10 1.11 1.12 1.13 1.14 1.15 1.16 1.17 1.18 1.19 1.20 1.21 1.22 1.23 1.24 1.25 1.26 1.27 1.28 1.29 1.30 1.31 1.32 1.33 1.34 1.35 1.36 1.37 1.38 1.39 1.40 1.41 1.42 1.43 1.44 1.45 1.46 1.47 1.48 1.49 1.50 1.51 1.52 1.53 1.54 1.55 1.56 1.57 1.58 1.59 1.60 1.61 1.62 1.63 1.64 1.65 1.66 1.67 1.68 1.69 1.70 1.71 1.72 1.73 1.74 1.75 1.76 1.77 1.78 1.79 1.80 1.81 1.82 1.83 1.84 1.85 1.86 1.87 1.88 1.89 1.90 1.91 1.92 1.93 1.94 1.95 1.96 1.97 1.98 1.99 2.00]
#define TRANSLUCENT_BLUR_INTENSITY 2.5 // [0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.0 3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.0 4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.0 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.0 7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.0 8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.0 9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9 10.0]

#define ENABLE_SKY_REFLECTION
#define ENABLE_SSR
#define SSR_RAYTRACING
#define SSR_RAYTRACING_STEPS 250 // [0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500]
#define SSR_BLUR_INTENSITY 1.0 // [0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.0]
#define SSR_ROUGHNESS_BLUR_INTENSITY 10.0 // [0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.0 3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.0 4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.0 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.0 7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.0 8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.0 9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9 10.0 10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8 10.9 11.0 11.1 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.0 12.1 12.2 12.3 12.4 12.5 12.6 12.7 12.8 12.9 13.0 13.1 13.2 13.3 13.4 13.5 13.6 13.7 13.8 13.9 14.0 14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.0 15.1 15.2 15.3 15.4 15.5 15.6 15.7 15.8 15.9 16.0 16.1 16.2 16.3 16.4 16.5 16.6 16.7 16.8 16.9 17.0 17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8 17.9 18.0 18.1 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.0 19.1 19.2 19.3 19.4 19.5 19.6 19.7 19.8 19.9 20.0]

#define SUNLIGHT_TYPE SPECULAR // [SPECULAR VANILLA]
#define SUNLIGHT_INTENSITY 5.0 // [0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.0 3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9 4.0 4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.0 5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9 6.0 6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.0 7.1 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.0 8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9 9.0 9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9 10.0]

#define WATER_TRANSPARENCY 0.50 // [0.00 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.30 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.40 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.60 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.70 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.80 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.90 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.00]
#define WATER_SMOOTHNESS 0.80 // [0.00 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.30 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.40 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.60 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.70 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.80 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.90]
#define WATER_REFLECTANCE 0.50 // [0.00 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.10 0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.20 0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.30 0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.40 0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.60 0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.70 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.80 0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.90 0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.00]

#endif /* !defined REFLECTIVE_VANILLA_CONFIG_GLSL_INCLUDED */

	void cubyz_packMain() {
	float vanillaAO = 0.0;
	vec4 albedo = col;
#	if defined USE_TEXTURES
		albedo *= texture(gtexture, uv0);
#	endif
	vec4 translucent = vec4(0.0);
	vec4 sunMoon = vec4(0.0);
#	if defined USE_ALPHA_TEST
		if (albedo.a < alphaTestRef) discard;
#	endif
#	if defined USE_LIGHTMAP
#		if defined GBUFFERS_BASIC
			/*
			 ** Leads have light levels, but chunk borders don't.
			 * And for whatever reason, chunk borders use gbuffers_basic
			 * instead of gbuffers_line, so we detect them with renderStage.
			*/
			if (renderStage != MC_RENDER_STAGE_DEBUG) {
				albedo *= texture(lightmap, uv1);
			}
#		else
			albedo *= texture(lightmap, uv1);
#		endif
#	endif
#	if defined GBUFFERS_ENTITIES
		albedo.rgb = mix(albedo.rgb, entityColor.rgb, entityColor.a);
#	endif
	vec3 fragPos = viewPos.xyz + cameraPosition;

#		if !defined GBUFFERS_SKY
#			if defined USE_TEXTURES && defined MC_NORMAL_MAP
				vec3 fNormal = normalize(vec3(texture(normals, uv0).rg * 2.0 - 1.0, sqrt(1.0 - dot(texture(normals, uv0).rg * 2.0 - 1.0, texture(normals, uv0).rg * 2.0 - 1.0))));
				fNormal = fNormal * tbnMatrix;
#			else
				vec3 fNormal = vNormal;
#			endif
#		else
			vec3 fNormal = normalize(cross(dFdx(fragPos), dFdy(fragPos)));
#		endif
		fNormal = mat3(gbufferModelViewInverse) * fNormal;

	float perceptualSmoothness = 0.0;
	float F0 = 0.0;

#	if defined USE_TEXTURES && defined MC_SPECULAR_MAP
		perceptualSmoothness = texture(specular, uv0).r;
		F0 = texture(specular, uv0).g;
#	endif

#	if defined USE_TEXTURES
		if (int(mcEntity) == 1) {
			perceptualSmoothness = WATER_SMOOTHNESS;
			albedo.a = WATER_TRANSPARENCY;
			F0 = WATER_REFLECTANCE;
		}
#	endif

	float roughness = (1.0 - perceptualSmoothness) * (1.0 - perceptualSmoothness);

#	if defined GBUFFERS_TRANSLUCENT
		albedo.a = mix(albedo.a, 1.0, fresnelSchlick(-normalize(relPos.xyz), fNormal, mix(0.04, dot(albedo.rgb, vec3(0.22, 0.707, 0.071)), F0)));
		translucent = albedo;
		albedo.a = 0.0;
#	endif

	vec4 fog = vec4(fogColor, getFog(fogMode, fogStart, fogEnd, viewPos));
#	if !defined GBUFFERS_SKYTEXTURED
		albedo.rgb = mix(albedo.rgb, fog.rgb, fog.a);
#	else
		sunMoon = albedo;
#	endif
	fog.a *= F0;

		/* colortex0 (gcolor) */
		fragData0 = albedo;

		/* colortex1 (gdepth, unused) */
		fragData1 = vec4(0.0);

		/* colortex2 (gnormal) */
		fragData2 = vec4((fNormal + 1.0) * 0.5, 1.0);

		/* colortex3 (composite) */
		fragData3 = translucent;

		/* colortex4 (gaux1) */
#		if defined USE_LIGHTMAP
#			if defined USE_TEXTURES
				fragData4 = vec4(uv1.y, F0, roughness, 1.0);
#			else
				fragData4 = vec4(uv1.y, vec2(0.0), 1.0);
#			endif
#		else
#			if defined USE_TEXTURES
				fragData4 = vec4(0.0, F0, roughness, 1.0);
#			else
				fragData4 = vec4(0.0, vec2(0.0), 1.0);
#			endif
#		endif

		/* colortex5 (gaux2) */
		fragData5 = fog;

		/* colortex6 (gaux3) */
		fragData6 = sunMoon;
	}
#endif /* defined GBUFFERS_FSH */

#if defined GBUFFERS_VSH
#	if defined GBUFFERS_LINE
		const float LINE_WIDTH  = 2.0;
		const float VIEW_SHRINK = 0.9609375 /* 1.0 - (1.0 / 256.0) */ ;
		const mat4 VIEW_SCALE   = mat4(
			VIEW_SHRINK, 0.0, 0.0, 0.0,
			0.0, VIEW_SHRINK, 0.0, 0.0,
			0.0, 0.0, VIEW_SHRINK, 0.0,
			0.0, 0.0, 0.0, 1.0
		);
		
		uniform float viewHeight, viewWidth;
#	endif

	uniform mat4 modelViewMatrix;
	uniform mat4 projectionMatrix;
	uniform mat4 gbufferModelView, gbufferModelViewInverse;
	uniform mat3 normalMatrix;
	uniform vec3 sunPosition, moonPosition, shadowLightPosition;
#	if defined USE_TEXTURES
		// Set a default value when the uniform is not bound.
		uniform mat4 textureMatrix = mat4(1.0);
#	endif
#	if defined USE_CHUNK_OFFSET
		uniform vec3 chunkOffset;
#	endif

#	if defined USE_TEXTURES
		in vec2 vaUV0;
#	endif
#	if defined USE_LIGHTMAP
		in ivec2 vaUV2;
#	endif
	in vec3 vaNormal;
	in vec3 vaPosition;
	in vec4 vaColor;
	
	

#	if defined USE_TEXTURES
		out vec2 uv0;
#	endif
#	if defined USE_LIGHTMAP
		out vec2 uv1;
#	endif
	out float mcEntity;
	out vec4 col;
	out vec4 viewPos;
	out vec4 relPos;
	out vec3 vNormal;
	out vec3 sunPos;
	out vec3 moonPos;
	out vec3 shadowLightPos;
	out mat3 tbnMatrix;

	void cubyz_packMain() {
#	if defined USE_TEXTURES
		uv0 = (textureMatrix * vec4(vaUV0, 0.0, 1.0)).xy;
#	endif
#	if defined USE_LIGHTMAP
		uv1 = vaUV2 * 0.00390625 /* (1.0 / 256.0) */ + 0.03125 /* (1.0 / 32.0) */ ;
#	endif
	mcEntity = 0.1;
	
	if (int(mc_Entity.x) == 10001) mcEntity = 1.1; // Water
	col = vaColor;

	vec4 worldPos = vec4(vaPosition, 1.0);
#	if defined USE_CHUNK_OFFSET
		worldPos.xyz += chunkOffset;
#	endif

	viewPos = modelViewMatrix * worldPos;
	relPos = worldPos;

	vec3 tangent  = normalize(normalMatrix * at_tangent.xyz);
	vec3 binormal = normalize(normalMatrix * cross(at_tangent.xyz, vaNormal) * at_tangent.w);
	
	vNormal    = normalize(normalMatrix * vaNormal);
	tbnMatrix  = transpose(mat3(tangent, binormal, vNormal));

#	if defined GBUFFERS_LINE
		vNormal = vec3(0.0);
#	endif

	sunPos         = normalize(mat3(gbufferModelViewInverse) * sunPosition);
	moonPos        = normalize(mat3(gbufferModelViewInverse) * moonPosition);
	shadowLightPos = normalize(mat3(gbufferModelViewInverse) * shadowLightPosition);

#		if defined GBUFFERS_LINE
		vec2 resolution   = vec2(viewWidth, viewHeight);
		vec4 linePosStart = projectionMatrix * (VIEW_SCALE * (modelViewMatrix * vec4(vaPosition, 1.0)));
		vec4 linePosEnd   = projectionMatrix * (VIEW_SCALE * (modelViewMatrix * vec4(vaPosition + vaNormal, 1.0)));

		vec3 ndc1 = linePosStart.xyz / linePosStart.w;
		vec3 ndc2 = linePosEnd.xyz   / linePosEnd.w;

		vec2 lineScreenDirection = normalize((ndc2.xy - ndc1.xy) * resolution);
		vec2 lineOffset = vec2(-lineScreenDirection.y, lineScreenDirection.x) * LINE_WIDTH / resolution;

		if (lineOffset.x < 0.0) lineOffset = -lineOffset;
		if (gl_VertexID % 2 != 0) lineOffset = -lineOffset;
			
			gl_Position = vec4((ndc1 + vec3(lineOffset, 0.0)) * linePosStart.w, linePosStart.w);
#		else
			gl_Position = projectionMatrix * (modelViewMatrix * worldPos);
#		endif
	}
#endif /* defined GBUFFERS_VSH */

#endif /* !defined GBUFFERS_GLSL_INCLUDED */