#version 460 core
// Generated by irisbridge from a shaderpack source. Do not edit.
#define MC_VERSION 12100
#define MC_GL_VERSION 460
#define MC_GLSL_VERSION 460
#define MC_MIPMAP_LEVEL 4
#define MC_RENDER_QUALITY 1.0
#define MC_SHADOW_QUALITY 1.0
#define MC_HAND_DEPTH 0.125
#define MC_NORMAL_MAP
#define MC_SPECULAR_MAP
#define MAX_COLOR_BUFFERS 16
#define IS_IRIS
#define IRIS_TAG_SUPPORT 2
#define IRIS_VERSION 10800
#define MC_RENDER_STAGE_NONE 0
#define MC_RENDER_STAGE_SKY 1
#define MC_RENDER_STAGE_SUNSET 2
#define MC_RENDER_STAGE_CUSTOM_SKY 3
#define MC_RENDER_STAGE_SUN 4
#define MC_RENDER_STAGE_MOON 5
#define MC_RENDER_STAGE_STARS 6
#define MC_RENDER_STAGE_VOID 7
#define MC_RENDER_STAGE_TERRAIN_SOLID 8
#define MC_RENDER_STAGE_TERRAIN_CUTOUT_MIPPED 9
#define MC_RENDER_STAGE_TERRAIN_CUTOUT 10
#define MC_RENDER_STAGE_ENTITIES 11
#define MC_RENDER_STAGE_BLOCK_ENTITIES 12
#define MC_RENDER_STAGE_DESTROY 13
#define MC_RENDER_STAGE_OUTLINE 14
#define MC_RENDER_STAGE_DEBUG 15
#define MC_RENDER_STAGE_HAND_SOLID 16
#define MC_RENDER_STAGE_TERRAIN_TRANSLUCENT 17
#define MC_RENDER_STAGE_TRIPWIRE 18
#define MC_RENDER_STAGE_PARTICLES 19
#define MC_RENDER_STAGE_CLOUDS 20
#define MC_RENDER_STAGE_RAIN_SNOW 21
#define MC_RENDER_STAGE_WORLD_BORDER 22
#define MC_RENDER_STAGE_HAND_TRANSLUCENT 23
#define MC_OS_LINUX
#define MC_GL_VENDOR_INTEL
#define MC_GL_RENDERER_INTEL

// ---- Cubyz compatibility shim ----
struct cubyz_FogParameters {vec4 color; float density; float start; float end; float scale;};
uniform cubyz_FogParameters cubyz_Fog;
layout(location = 0) out vec4 cubyz_FragData[1];
// pack declares its own `texture`; renamed to `gtexture`, as Iris does
vec4 cubyz_texture2D(sampler2D s, vec2 c) {return texture(s, c);}
vec4 cubyz_texture2D(sampler2D s, vec2 c, float b) {return texture(s, c, b);}

// ---- Cubyz vertex prologue ----
layout(binding = 23) uniform sampler2DArray cubyz_blockTextures;
layout(binding = 24) uniform sampler2DArray cubyz_emissionTextures;
layout(binding = 25) uniform sampler2DArray cubyz_reflectivityTextures;
flat in int cubyz_textureLayer;
/// Divides a fluid's texture by the tint the vertex stage put in glColor, so the pack sees
/// Minecraft's pair - a grey texture and a coloured glColor - whose product is the colour
/// Cubyz authored - and lifts its alpha to Minecraft's water alpha. (1, 1, 1, 0) for every
/// other block. See `cubyz_applyVertexTint`.
flat in vec4 cubyz_textureUntint;

/// Cubyz animates textures by swapping array layers, so the live layer is looked up per
/// fragment exactly as `chunks/chunk_fragment.frag` does.
layout(std430, binding = 1) buffer _cubyzAnimatedTexture {float cubyzAnimatedTexture[];};

vec3 cubyz_layerCoord(vec2 uv) {
    return vec3(uv, cubyzAnimatedTexture[cubyz_textureLayer]);
}

vec4 cubyz_untint(vec4 texel) {
    return vec4(texel.rgb*cubyz_textureUntint.rgb, max(texel.a, cubyz_textureUntint.a));
}

// Every sampling call whose first argument names the block texture is rewritten to this,
// keeping the sampler as the first argument so the overloads pick the right arity.
//
// A plain `#define` of the sampler name cannot do the job on its own: packs pass a
// two-component coordinate, and there is no valid overload of `texture` taking
// `(sampler2DArray, vec2)` no matter what the sampler is called. The call site has to
// change too, and only where it targets the block texture — the same program samples
// `lightmap` and `depthtex0`, which really are 2D.
//
// Three helper names, not one, because `texture(s, c, x)` and `textureLod(s, c, x)` are the
// same shape with different meanings — a bias against the implicit level, versus an explicit
// level. One name could only carry one of those bodies, so the other reading was silently
// substituted wherever a pack used it.
//
// Every array flavour goes through `cubyz_untint`: the only sampler2DArray a pack's call can
// name is the block texture, and a fluid's texture has to arrive untinted.
vec4 cubyz_sampleArray(sampler2DArray s, vec2 c) {return cubyz_untint(texture(s, cubyz_layerCoord(c)));}
vec4 cubyz_sampleArray(sampler2DArray s, vec2 c, float b) {return cubyz_untint(texture(s, cubyz_layerCoord(c), b));}
vec4 cubyz_sampleArray(sampler2DArray s, vec2 c, int b) {return cubyz_untint(texture(s, cubyz_layerCoord(c), float(b)));}
vec4 cubyz_sampleArray(sampler2DArray s, vec3 c) {return cubyz_untint(texture(s, cubyz_layerCoord(c.xy)));}
vec4 cubyz_sampleArrayLod(sampler2DArray s, vec2 c, float l) {return cubyz_untint(textureLod(s, cubyz_layerCoord(c), l));}
vec4 cubyz_sampleArrayLod(sampler2DArray s, vec2 c, int l) {return cubyz_untint(textureLod(s, cubyz_layerCoord(c), float(l)));}
vec4 cubyz_sampleArrayLod(sampler2DArray s, vec3 c, float l) {return cubyz_untint(textureLod(s, cubyz_layerCoord(c.xy), l));}
// The parallax march form. photon reads every texture through
// `#define read_tex(x) textureGrad(x, parallax_uv, uv_gradient[0], uv_gradient[1])`, so
// without these its `gbuffers_water` redirected correctly and then landed on a signature
// nobody had written.
vec4 cubyz_sampleArrayGrad(sampler2DArray s, vec2 c, vec2 dx, vec2 dy) {return cubyz_untint(textureGrad(s, cubyz_layerCoord(c), dx, dy));}
vec4 cubyz_sampleArrayGrad(sampler2DArray s, vec3 c, vec2 dx, vec2 dy) {return cubyz_untint(textureGrad(s, cubyz_layerCoord(c.xy), dx, dy));}
// Integer texel coordinates: the layer joins as an integer and nothing is scaled.
vec4 cubyz_fetchArray(sampler2DArray s, ivec2 c, int l) {return cubyz_untint(texelFetch(s, ivec3(c, int(cubyzAnimatedTexture[cubyz_textureLayer])), l));}
// A parameter or local of the pack's own function that merely happens to be spelled like the
// block texture - Nostalgia's noise fetch takes `sampler2D tex` - is an ordinary 2D sampler.
// The redirect keys on spelling and cannot tell; overload resolution can, and this is the one
// place the type is actually known. Each is a plain passthrough.
vec4 cubyz_sampleArray(sampler2D s, vec2 c) {return texture(s, c);}
vec4 cubyz_sampleArray(sampler2D s, vec2 c, float b) {return texture(s, c, b);}
vec4 cubyz_sampleArray(sampler2D s, vec2 c, int b) {return texture(s, c, float(b));}
vec4 cubyz_sampleArray(sampler2D s, vec3 c) {return texture(s, c.xy);}
vec4 cubyz_sampleArrayLod(sampler2D s, vec2 c, float l) {return textureLod(s, c, l);}
vec4 cubyz_sampleArrayLod(sampler2D s, vec2 c, int l) {return textureLod(s, c, float(l));}
vec4 cubyz_sampleArrayLod(sampler2D s, vec3 c, float l) {return textureLod(s, c.xy, l);}
vec4 cubyz_sampleArrayGrad(sampler2D s, vec2 c, vec2 dx, vec2 dy) {return textureGrad(s, c, dx, dy);}
vec4 cubyz_sampleArrayGrad(sampler2D s, vec3 c, vec2 dx, vec2 dy) {return textureGrad(s, c.xy, dx, dy);}
vec4 cubyz_fetchArray(sampler2D s, ivec2 c, int l) {return texelFetch(s, c, l);}

// ---- the same, dispatched by sampler *type* rather than by name ----
//
// For a sampling call inside a pack's own macro, where the sampler is the macro's parameter
// and its identity is only knowable after preprocessing. Three of the six packs in the
// corpus wrap every texture read this way. Overload resolution answers per expansion what
// the token scan cannot answer at all; see `glsl.MacroDispatch`.
//
// The `sampler2D` overloads are exact passthroughs, so a macro invoked with an ordinary 2D
// sampler behaves precisely as it did before.
vec4 cubyz_sampleAny(sampler2D s, vec2 c) {return texture(s, c);}
vec4 cubyz_sampleAny(sampler2D s, vec2 c, float b) {return texture(s, c, b);}
vec4 cubyz_sampleAny(sampler2D s, vec2 c, int b) {return texture(s, c, float(b));}
vec4 cubyz_sampleAny(sampler2D s, vec3 c) {return texture(s, c.xy);}
vec4 cubyz_sampleAnyLod(sampler2D s, vec2 c, float l) {return textureLod(s, c, l);}
vec4 cubyz_sampleAnyLod(sampler2D s, vec2 c, int l) {return textureLod(s, c, float(l));}
vec4 cubyz_sampleAnyGrad(sampler2D s, vec2 c, vec2 dx, vec2 dy) {return textureGrad(s, c, dx, dy);}
vec4 cubyz_fetchAny(sampler2D s, ivec2 c, int l) {return texelFetch(s, c, l);}
vec4 cubyz_sampleAny(sampler2DArray s, vec2 c) {return cubyz_sampleArray(s, c);}
vec4 cubyz_sampleAny(sampler2DArray s, vec2 c, float b) {return cubyz_sampleArray(s, c, b);}
vec4 cubyz_sampleAny(sampler2DArray s, vec2 c, int b) {return cubyz_sampleArray(s, c, b);}
vec4 cubyz_fetchAny(sampler2DArray s, ivec2 c, int l) {return cubyz_fetchArray(s, c, l);}
vec4 cubyz_sampleAny(sampler2DArray s, vec3 c) {return cubyz_sampleArray(s, c);}
vec4 cubyz_sampleAnyLod(sampler2DArray s, vec2 c, float l) {return cubyz_sampleArrayLod(s, c, l);}
vec4 cubyz_sampleAnyLod(sampler2DArray s, vec2 c, int l) {return cubyz_sampleArrayLod(s, c, l);}
vec4 cubyz_sampleAnyGrad(sampler2DArray s, vec2 c, vec2 dx, vec2 dy) {return cubyz_sampleArrayGrad(s, c, dx, dy);}

// ---- LabPBR material data, synthesised from Cubyz's own material arrays ----
//
// Cubyz has no LabPBR textures, but it does carry two of the three things one encodes:
// per-texel reflectivity and per-texel emission. Handing packs a neutral constant throws
// that away and makes every surface identically matte; this translates what exists and is
// explicit about what does not.
//
// The sampler argument is accepted and ignored. It has to stay in the call so the pack's
// own `uniform sampler2D specular;` declaration is still referenced — dropping it would
// leave a declared-but-unused sampler and change nothing else.
vec4 cubyz_labPbrSpecular(vec2 uv) {
    vec3 coord = cubyz_layerCoord(uv);
    float reflectivity = texture(cubyz_reflectivityTextures, coord).a;
    float emission = texture(cubyz_emissionTextures, coord).r;

    // Cubyz has no roughness. `chunk_fragment.frag` samples a perfect mirror,
    // `fixedCubeMapLookup(reflect(direction, normal))`, and scales it by reflectivity, so a
    // reflective texel is a perfectly smooth surface whose reflectance is the reflectivity:
    // smoothness 1.0 and F0 from the value. A texel with no reflectivity is Iris's own default
    // for a block without a specular map, all zeros (`PBRType.SPECULAR`, 0x00000000), which is
    // the value every pack's hardcoded materials were written against.
    //
    // This read `smoothness = reflectivity` before, on the argument that the engine treats a
    // reflective block as a smooth one - but 27/255 is not smooth, it is rough, and packs took
    // it at its word. Bliss overrides its hardcoded water material whenever `specular.r > 0`
    // (`all_translucent.fsh:727`), turned a smoothness of 0.106 into a roughness of 0.8, and
    // its `visibilityFactor`, exp2(-4 * roughness^3 / f0), came out at 1.5e-6: every
    // reflection off, sun glint included, and the lake a flat dark teal (2026-09-05).
    float smoothness = reflectivity > 0.0 ? 1.0 : 0.0;
    // Held below the 230/255 metal threshold. Cubyz has no metalness concept, and crossing
    // into the metal range makes a pack tint its reflections by the albedo and drop diffuse
    // entirely — a large, wrong change rather than a subtle one.
    float f0 = min(reflectivity, 229.0/255.0);

    // Cubyz compares `emission.r*4` against the light value, so 0.25 already means fully lit;
    // the same factor is applied here so a block glows in the pack at the strength it glows
    // in the engine. 255/255 is LabPBR's "no emission" sentinel, so genuine emission is
    // capped just below it.
    float emissiveness = min(emission*4.0, 254.0/255.0);

    // Blue is porosity/SSS. Cubyz's absorption is a translucency tint rather than either of
    // those, so it stays unmapped instead of being forced into a channel that means
    // something else.
    return vec4(smoothness, f0, 0.0, emissiveness);
}

// One name for all three flavours here, unlike the block texture: the value is synthesised
// rather than sampled, so a level or a derivative has nothing to select and every overload
// returns the same thing. The arities still have to exist, or a redirected call lands on a
// signature that was never declared.
vec4 cubyz_sampleSpecular(sampler2D s, vec2 c) {return cubyz_labPbrSpecular(c);}
vec4 cubyz_sampleSpecular(sampler2D s, vec2 c, float b) {return cubyz_labPbrSpecular(c);}
vec4 cubyz_sampleSpecular(sampler2D s, vec2 c, int l) {return cubyz_labPbrSpecular(c);}
vec4 cubyz_sampleSpecular(sampler2D s, vec3 c) {return cubyz_labPbrSpecular(c.xy);}
vec4 cubyz_sampleSpecular(sampler2D s, vec3 c, float l) {return cubyz_labPbrSpecular(c.xy);}
vec4 cubyz_sampleSpecular(sampler2D s, vec2 c, vec2 dx, vec2 dy) {return cubyz_labPbrSpecular(c);}
vec4 cubyz_sampleSpecular(sampler2D s, vec3 c, vec2 dx, vec2 dy) {return cubyz_labPbrSpecular(c.xy);}
// A texel fetch against the material map: the texel is turned back into a coordinate on
// Cubyz's own arrays, whose layers are all one size.
vec4 cubyz_sampleSpecular(sampler2D s, ivec2 c, int l) {return cubyz_labPbrSpecular((vec2(c) + 0.5) / vec2(textureSize(cubyz_emissionTextures, 0).xy));}

// Packs spell the block texture several ways depending on their vintage.
#define gtexture cubyz_blockTextures
#define gcolor cubyz_blockTextures
#define tex cubyz_blockTextures
#define texture0 cubyz_blockTextures


// ---- shaderpack source ----
// Deliberately no wave animation, no color tint change here - the
// brief was "purely improve vanilla visuals, stay simple", so water
// keeps its vanilla look and texture and just gains the same dynamic
// shadow/lighting treatment as everything else, for consistency.

#ifndef SETTINGS_GLSL
#define SETTINGS_GLSL

//////////////////////////// SHADOWS ////////////////////////////

// Tension worth naming: "pixel-perfect" and "fast on a UHD 630" pull
// in opposite directions - shadow resolution is the single biggest
// cost lever on integrated GPUs. 1024 is the tuned-for-UHD-630
// default; raise it if you're on better hardware and want crisper
// far-range edges.
#define SHADOW_RES 1024 // [512 1024 1536 2048]

// Kept modest on purpose: shadow distance and effective resolution
// trade off directly (same texel budget spread over less world space
// = crisper). A tight distance is also more honest about what
// "pixel-perfect" can mean at 1024 - claiming pixel-perfect shadows
// out to 200 blocks on this resolution would just be wrong.
#define SHADOW_DISTANCE 72.0 // [48.0 64.0 72.0 96.0]

// Normal-offset bias, in shadow texels. This is what actually fixes
// jitter/acne, NOT a big depth bias (which causes peter-panning
// instead) and NOT PCF blurring (which fights the "pixel-perfect"
// goal). See lib/shadows.glsl for how it's applied.
#define NORMAL_OFFSET_TEXELS 1.4 // [0.8 1.1 1.4 1.8]

//////////////////////////// GOD RAYS ////////////////////////////

#define GODRAYS 1 // [0 1]

// Hard-capped low on purpose - iteration-heavy loops are close to
// the worst case for a UHD 630's weak parallelism.
#define GODRAY_STEPS 8 // [4 6 8 12]

// How far the raymarch reaches, in blocks. God rays are a near-
// camera effect - marching further just burns steps on a region
// where the effect isn't visible anyway.
#define GODRAY_DISTANCE 40.0 // [24.0 32.0 40.0 56.0]

#define GODRAY_INTENSITY 0.28 // [0.15 0.22 0.28 0.38]

//////////////////////////// LIGHTING ////////////////////////////

// Ambient floor - stops caves/night terrain going pure black. Purely
// a function of vanilla's own sky-light lightmap channel, so it's
// stable regardless of camera angle.
#define MIN_AMBIENT 0.05

#endif // SETTINGS_GLSL
#ifndef COMMON_GLSL
#define COMMON_GLSL

float expFog(float dist, float fogStart, float fogEnd) {
    float f = clamp((dist - fogStart) / (fogEnd - fogStart), 0.0, 1.0);
    return f * f * (3.0 - 2.0 * f);
}

#endif // COMMON_GLSL
#ifndef LIGHTING_GLSL
#define LIGHTING_GLSL

#ifndef SETTINGS_GLSL
#define SETTINGS_GLSL

//////////////////////////// SHADOWS ////////////////////////////

// Tension worth naming: "pixel-perfect" and "fast on a UHD 630" pull
// in opposite directions - shadow resolution is the single biggest
// cost lever on integrated GPUs. 1024 is the tuned-for-UHD-630
// default; raise it if you're on better hardware and want crisper
// far-range edges.
#define SHADOW_RES 1024 // [512 1024 1536 2048]

// Kept modest on purpose: shadow distance and effective resolution
// trade off directly (same texel budget spread over less world space
// = crisper). A tight distance is also more honest about what
// "pixel-perfect" can mean at 1024 - claiming pixel-perfect shadows
// out to 200 blocks on this resolution would just be wrong.
#define SHADOW_DISTANCE 72.0 // [48.0 64.0 72.0 96.0]

// Normal-offset bias, in shadow texels. This is what actually fixes
// jitter/acne, NOT a big depth bias (which causes peter-panning
// instead) and NOT PCF blurring (which fights the "pixel-perfect"
// goal). See lib/shadows.glsl for how it's applied.
#define NORMAL_OFFSET_TEXELS 1.4 // [0.8 1.1 1.4 1.8]

//////////////////////////// GOD RAYS ////////////////////////////

#define GODRAYS 1 // [0 1]

// Hard-capped low on purpose - iteration-heavy loops are close to
// the worst case for a UHD 630's weak parallelism.
#define GODRAY_STEPS 8 // [4 6 8 12]

// How far the raymarch reaches, in blocks. God rays are a near-
// camera effect - marching further just burns steps on a region
// where the effect isn't visible anyway.
#define GODRAY_DISTANCE 40.0 // [24.0 32.0 40.0 56.0]

#define GODRAY_INTENSITY 0.28 // [0.15 0.22 0.28 0.38]

//////////////////////////// LIGHTING ////////////////////////////

// Ambient floor - stops caves/night terrain going pure black. Purely
// a function of vanilla's own sky-light lightmap channel, so it's
// stable regardless of camera angle.
#define MIN_AMBIENT 0.05

#endif // SETTINGS_GLSL

uniform vec3 shadowLightPosition;

vec3 getShadowLightDirection() {
    return normalize(shadowLightPosition);
}

// Deliberately just N.L, no view-vector term anywhere in this pack.
// Any dot(normal, viewDir) - fresnel, rim light, cheap specular - by
// definition changes as you rotate the camera even though nothing in
// the world moved, which is exactly the "tone shifts as I look
// around" bug you're asking to avoid. So it's just not here.
float diffuse(vec3 normal, vec3 lightDir) {
    return max(dot(normal, lightDir), 0.0);
}

// day/night as a plain function of sun elevation - camera-independent,
// stable no matter which way you're facing.
float getDayFactor(vec3 lightDir) {
    return clamp(lightDir.y * 1.3 + 0.15, 0.0, 1.0);
}

vec3 getSunMoonColor(float dayFactor) {
    vec3 day   = vec3(1.0, 1.0, 1.0);
    vec3 night = vec3(0.45, 0.5, 0.65);
    return mix(night, day, smoothstep(0.0, 0.4, dayFactor));
}

#endif // LIGHTING_GLSL
#ifndef SHADOWS_GLSL
#define SHADOWS_GLSL

#ifndef SETTINGS_GLSL
#define SETTINGS_GLSL

//////////////////////////// SHADOWS ////////////////////////////

// Tension worth naming: "pixel-perfect" and "fast on a UHD 630" pull
// in opposite directions - shadow resolution is the single biggest
// cost lever on integrated GPUs. 1024 is the tuned-for-UHD-630
// default; raise it if you're on better hardware and want crisper
// far-range edges.
#define SHADOW_RES 1024 // [512 1024 1536 2048]

// Kept modest on purpose: shadow distance and effective resolution
// trade off directly (same texel budget spread over less world space
// = crisper). A tight distance is also more honest about what
// "pixel-perfect" can mean at 1024 - claiming pixel-perfect shadows
// out to 200 blocks on this resolution would just be wrong.
#define SHADOW_DISTANCE 72.0 // [48.0 64.0 72.0 96.0]

// Normal-offset bias, in shadow texels. This is what actually fixes
// jitter/acne, NOT a big depth bias (which causes peter-panning
// instead) and NOT PCF blurring (which fights the "pixel-perfect"
// goal). See lib/shadows.glsl for how it's applied.
#define NORMAL_OFFSET_TEXELS 1.4 // [0.8 1.1 1.4 1.8]

//////////////////////////// GOD RAYS ////////////////////////////

#define GODRAYS 1 // [0 1]

// Hard-capped low on purpose - iteration-heavy loops are close to
// the worst case for a UHD 630's weak parallelism.
#define GODRAY_STEPS 8 // [4 6 8 12]

// How far the raymarch reaches, in blocks. God rays are a near-
// camera effect - marching further just burns steps on a region
// where the effect isn't visible anyway.
#define GODRAY_DISTANCE 40.0 // [24.0 32.0 40.0 56.0]

#define GODRAY_INTENSITY 0.28 // [0.15 0.22 0.28 0.38]

//////////////////////////// LIGHTING ////////////////////////////

// Ambient floor - stops caves/night terrain going pure black. Purely
// a function of vanilla's own sky-light lightmap channel, so it's
// stable regardless of camera angle.
#define MIN_AMBIENT 0.05

#endif // SETTINGS_GLSL

// Declared as sampler2DShadow (not a plain sampler2D) to get
// hardware-accelerated shadow comparison: the GPU bilinearly filters
// the DEPTH COMPARE RESULT itself across the 4 nearest texels, in one
// texture fetch, for free. That's what actually gives a crisp-but-
// not-jittery edge here - a manually-filtered depth value compared
// afterward would only smooth the depth threshold, not the edge
// itself; hardware shadow sampling smooths the edge directly.
uniform sampler2DShadow shadowtex1;
uniform mat4 shadowProjection;
uniform mat4 shadowModelView;
uniform mat4 gbufferModelViewInverse;

// One texel's approximate world-space size, used to scale the normal
// offset below. SHADOW_DISTANCE is the orthographic frustum's rough
// half-extent, so 2x that spread over SHADOW_RES texels gives a
// reasonable per-texel size estimate.
float shadowTexelWorldSize() {
    return (SHADOW_DISTANCE * 2.0) / float(SHADOW_RES);
}

vec3 toShadowScreenSpace(vec3 worldPos) {
    vec4 shadowClip = shadowProjection * (shadowModelView * vec4(worldPos, 1.0));
    return shadowClip.xyz / shadowClip.w * 0.5 + 0.5;
}

// Normal-offset bias: push the sample point along the surface normal,
// in WORLD space, before projecting into shadow space - not a depth
// bias tweak. This is what actually kills both shadow acne and the
// swimming/shimmering that shows up as the camera moves, without
// needing PCF blur (which would soften edges you explicitly want
// crisp) or a large depth bias (which causes visible peter-panning,
// shadows detaching from the objects casting them).
float sampleShadow(vec3 viewPos, vec3 viewNormal) {
    vec4 worldPos4 = gbufferModelViewInverse * vec4(viewPos, 1.0);
    vec3 worldNormal = mat3(gbufferModelViewInverse) * viewNormal;

    float offset = shadowTexelWorldSize() * NORMAL_OFFSET_TEXELS;
    vec3 worldPos = worldPos4.xyz + worldNormal * offset;

    vec3 shadowScreen = toShadowScreenSpace(worldPos);

    if (shadowScreen.x < 0.0 || shadowScreen.x > 1.0 ||
        shadowScreen.y < 0.0 || shadowScreen.y > 1.0 ||
        shadowScreen.z < 0.0 || shadowScreen.z > 1.0) {
        return 1.0;
    }

    // Single hardware-filtered compare, one fetch. The GPU compares
    // the biased reference depth against the 4 nearest shadow-map
    // texels and blends the pass/fail results - not the depth values
    // - giving a smoothly-positioned edge instead of a texel-snapped
    // staircase, without turning into a soft PCF blur.
    float bias = 0.0006;
    return gtexture(shadowtex1, vec3(shadowScreen.xy, shadowScreen.z - bias));
}

#endif // SHADOWS_GLSL


uniform sampler2D lightmap;
uniform float far;

in vec2 texCoord;
in vec2 lightMapCoord;
in vec3 normal;
in vec3 viewPos;
in vec4 vertexColor;

void main() {
    vec4 albedo = cubyz_sampleArray(gtexture, texCoord) * vertexColor;
    if (albedo.a < 0.05) discard;

    vec3 lightDir = getShadowLightDirection();
    float dayFactor = getDayFactor(lightDir);
    vec3 lightColor = getSunMoonColor(dayFactor);
    vec3 lightmapColor = cubyz_texture2D(lightmap, lightMapCoord).rgb;

    float ndotl = diffuse(normal, lightDir);
    float shadow = sampleShadow(viewPos, normal);
    float skyVisibility = lightMapCoord.y;
    float directLight = ndotl * shadow * skyVisibility;
    float ambient = max(MIN_AMBIENT, (1.0 - skyVisibility) * 0.03);

    vec3 litColor = albedo.rgb * lightmapColor * (ambient + 0.55 + directLight * lightColor * 0.5);

    float dist = length(viewPos);
    float fogAmount = expFog(dist, far * 0.8, far);
    litColor = mix(litColor, cubyz_Fog.color.rgb, fogAmount);

    cubyz_FragData[0] = vec4(litColor, albedo.a);
}
