blend.clrwl_gbuffers=off

blend.clrwl_gbuffers_additive.colortex1=ONE ONE ZERO ONE
blend.clrwl_gbuffers_additive.colortex2=off

blend.clrwl_gbuffers_lightning.colortex1=SRC_ALPHA ONE ZERO ONE
blend.clrwl_gbuffers_lightning.colortex2=off

blend.clrwl_gbuffers_glint=SRC_COLOR ONE ZERO ONE

blend.clrwl_gbuffers_translucent=SRC_ALPHA ONE_MINUS_SRC_ALPHA ZERO ZERO

#if COLORWHEEL_VERSION >= 10205
	blend.clrwl_gbuffers_damagedblock.colortex1=DST_COLOR SRC_COLOR ONE ZERO
	blend.clrwl_gbuffers_damagedblock.colortex2=off
#else
	# See shader files.
	blend.clrwl_gbuffers_damagedblock=DST_COLOR SRC_COLOR ZERO ONE
#endif

blend.clrwl_shadow=off
blend.clrwl_shadow_additive=off
blend.clrwl_shadow_lightning=off
blend.clrwl_shadow_glint=off
blend.clrwl_shadow_translucent=off

shadow.enabled=true
oit=false
