vignette=false
clouds=off
sky=off
stars=off
rain.depth=true

customTexture.blueNoiseTex = textures/noise.png

sliders=WATER_WAVE_STRENGTH FOLIAGE_WAVE_STRENGTH SHADOW_RESOLUTION SSR_DISTANCE SSR_STEPS SHADOW_QUALITY

// Copyright (c) 2026 skotah. All rights reserved. //