oldLighting=true
vignette=true

uniform.float.framemod8 = frameCounter % 8

screen=<empty> <empty> BY TYPE_AA <empty> <empty> [LT] [PP]

screen.LT=<empty> <empty> shadowDistance shadowMapResolution FOG
screen.PP=<empty> <empty> MOTION_BLUR MOTION_BLURRING_STRENGTH

sliders=shadowDistance shadowMapResolution MOTION_BLURRING_STRENGTH