# block.properties
# Asocia bloques a un ID que leemos en los shaders vía mc_Entity.x.
# Los IDs deben coincidir con los #define de lib/common.glsl.

block.10000 = minecraft:water
block.10001 = minecraft:lava
block.10002 = minecraft:ice minecraft:packed_ice minecraft:blue_ice minecraft:frosted_ice
block.10003 = minecraft:nether_portal

# --- Vegetación que ondea al viento (lib/wind.glsl) ---
# Hojas: ondean como bloque entero (suave).
block.10020 = minecraft:oak_leaves minecraft:spruce_leaves minecraft:birch_leaves minecraft:jungle_leaves minecraft:acacia_leaves minecraft:dark_oak_leaves minecraft:mangrove_leaves minecraft:cherry_leaves minecraft:azalea_leaves minecraft:flowering_azalea_leaves
# Plantas: ondean desde la base (raíz fija, punta se mueve).
block.10021 = minecraft:short_grass minecraft:tall_grass minecraft:fern minecraft:large_fern minecraft:dandelion minecraft:poppy minecraft:blue_orchid minecraft:allium minecraft:azure_bluet minecraft:red_tulip minecraft:orange_tulip minecraft:white_tulip minecraft:pink_tulip minecraft:oxeye_daisy minecraft:cornflower minecraft:lily_of_the_valley minecraft:wheat minecraft:carrots minecraft:potatoes minecraft:beetroots minecraft:sugar_cane minecraft:sweet_berry_bush minecraft:seagrass minecraft:tall_seagrass minecraft:kelp minecraft:kelp_plant
