# Enabled default clouds if ingame setting is set to 1.
#if Clouds == 1
    clouds=fancy
#else
    clouds=off
#endif

# Toggle programs
program.shadow.enabled=Shadows || Volumetric_Lighting
program.composite.enabled=Bloom || Godrays || Volumetric_Lighting
program.composite1.enabled=Bloom || Godrays || Volumetric_Lighting || Lens_Flares || Celshading || Fog
program.composite2.enabled=TAA
progam.deferred1.enabled=metallicRefl || polishedRefl || RainReflections || (VOXY && waterRefl)

#particles.before.deferred=true
#particles.ordering=before
#rain.depth=true

# The DH shadow pass is automatically enabled. It can be turned on or off with the shader property dhShadow.enabled.
# Distant Horizons has no set shadow distance; all chunks will be rendered.
dhShadow.enabled=false

# Enable or disable old hand light 
# Backwards compatibility for shader packs not supporting main and off hand.
# When enabled uses the handheld item with higher light value for the main hand.  
# The old hand light is also controlled by "Video Settings -> Shaders -> Old Hand Light" with higher priority
#oldHandLight=true|false

# Enable or disable old block lighting with fixed multiplier
# The old block lighting is also controlled by "Video Settings -> Shaders -> Old Lighting" with higher priority
# oldLighting=true|false
oldLighting=false

# Enable or disable rendering of translucent blocks (water, stained glass) in the shadow pass
# shadowTranslucent=true|false
shadowTranslucent=true

# Frustum culling
# Enable or disable frustum culling
frustum.culling=true

# Enable or disable the dynamic hand light from "Dynamic Lights"
# This option can be used to disable the dynamic hand light from "Dynamic Lights" if the shader implements its own hand light.
# dynamicHandLight=true|false

# Enable or disable underwater screen overlay
underwaterOverlay=false

# Enable or disable sun rendering
# sun=true|false

# Enable or disable moon rendering
# moon=true|false

screen=SSDO ao_strength Shadows shadowMapResolution PCSS shadowDistance waterRefl Clouds TAA TAA_sharpness Bloom bloom_strength Motionblur MB_strength Fog wFogDensity <empty> [ADVANCED_SCREEN]

screen.ADVANCED_SCREEN=[COLORS_SCREEN] [WAVING_SCREEN] [SKY_SCREEN] [FOG_SCREEN] [NORMALMAP_SCREEN] [REFLECTIONS_SCREEN] [SHADOWS_SCREEN] [DOF_SCREEN] [SHADING_SCREEN] [EMISSIVE_SCREEN] [Debug] MobsFlashRed Whiteworld
screen.COLORS_SCREEN=Brightness Contrast [WATERC_SCREEN] [LIGHTINGC_SCREEN]
screen.WATERC_SCREEN=watertex <empty> customWaterC waterCR <empty> waterCG <empty> waterCB <empty> waterA
screen.LIGHTINGC_SCREEN=HandLight <empty> eyeLight <empty> light_brightness <empty> r_multiplier <empty> g_multiplier <empty> b_multiplier
screen.WAVING_SCREEN=animationSpeed <empty> Waving_Grass Waving_Tallgrass Waving_Entities Waving_Leaves Waving_Vines Waving_Fire Waving_Lanterns Waving_Lava Waving_Lilypads Waving_Water waveSize waves_amplitude
screen.SKY_SCREEN=Lens_Flares Lens_Flares_Strength Rain_Drops <empty> Godrays Godrays_Density Volumetric_Lighting VL_amount Clouds cloudsIT <empty> cloud_height defskybox customStars sunPathRotation WeatherAngle WeatherIntensity Moonlight
screen.NORMALMAP_SCREEN=nMap POM_RES <empty> POM_DEPTH <empty> POM_DIST WaterParallax waterheight
screen.FOG_SCREEN=Fog wFogDensity Underwater_Fog uFogDensity
screen.REFLECTIONS_SCREEN=Reflections <empty> waterRefl Refraction Caustics causticsStrength iceRefl <empty> Cloud_reflection <empty> metallicRefl metalNoise polishedRefl <empty> RainReflections rainNoise <empty> BiomeCheck
screen.SHADOWS_SCREEN=Shadows shadowMapResolution PCSS shadowDistance ColoredShadows raytracedShadows grass_shadows shadow_samples Nearshadowplane Farshadowplane
screen.DOF_SCREEN=Depth_of_Field DoF_Strength smoothDof <empty> Distance_Blur Dof_Distance_View
screen.SHADING_SCREEN=Celshading Celborder <empty> Celradius
screen.EMISSIVE_SCREEN=minlight <empty> emissive_R <empty> emissive_G <empty> emissive_B

screen.Debug=Showbuffer <empty> IRIS_END_FIX
#screen.Experimental=*

sliders=TAA_sharpness Godrays_Density VL_amount ao_strength Celborder Celradius eyeLight emissive_R emissive_G emissive_B waterCR waterCG waterCB waterA light_brightness r_multiplier g_multiplier b_multiplier shadow_samples Nearshadowplane Farshadowplane shadowDistance Brightness Contrast DoF_Strength Dof_Distance_View wFogDensity uFogDensity POM_DIST POM_DEPTH minlight cloudsIT Cloud_reflection cloud_height skyboxblendfactor sunPathRotation rainNoise waveSize causticsStrength AS_sharpening waves_amplitude wtexblend metalNoise WeatherIntensity bloom_strength MB_strength shadowMapResolution

# Biome temperature
# Rain/snow is rendered for "biome_precipitation != PPT_NONE". If "temperature >= 0.15" rain is rendered, otherwise snow. 
uniform.float.BiomeTemp=temperature

# Used for TAA
#uniform.vec2.texelSize=vec2(1.0/viewWidth,1.0/viewHeight) Doesn't work in 1.7.10
uniform.int.framemod8=fmod(frameCounter, 8)