# ============================================================================
# Configurações do Iris / Optifine
# ============================================================================

# Coloured Lights SSBO
iris.features.required = SSBO COMPUTE_SHADERS
bufferObject.0 = 2097152
bufferObject.1 = 8404992
bufferObject.3 = 16384
allowConcurrentCompute = false

# Screen Setup (Organização dos Menus)
screen=<empty> <empty> [LIGHTING] [SHADOW] [CAVE] [FOG] [GODRAYS] [COLOR] [SKY] [COLOURED_LIGHTS]

screen.LIGHTING=<empty> <empty> SUNLIGHT_I MOONLIGHT_I AMBIENT_I AMBIENT_NIGHT_I SKYLIGHT_I BLOCKLIGHT_I NIGHT_DIM SPECULAR_POWER SPECULAR_INTENSITY
screen.SHADOW=<empty> <empty> shadowMapResolution shadowDistance SHADOW_RANGE SHADOW_RADIUS
screen.CAVE=<empty> <empty> CAVE_THRESHOLD CAVE_POWER CAVE_STRENGTH NIGHT_CAVE_THRESHOLD NIGHT_CAVE_POWER NIGHT_CAVE_STRENGTH
screen.FOG=<empty> <empty> FOG_DENSITY FOG_DENSITY_NIGHT WATER_FOG_DENSITY
screen.GODRAYS=<empty> <empty> GOD_RAY_SAMPLES GOD_RAY_INTENSITY MOON_RAY_FACTOR
screen.COLOR=<empty> <empty> EXPOSURE_DAY EXPOSURE_NIGHT
screen.SKY=<empty> <empty> CLOUD_STEPS CLOUD_DENSITY CLOUD_ABSORPTION CLOUD_COVERAGE CLOUD_HEIGHT_MIN CLOUD_HEIGHT_MAX
screen.COLOURED_LIGHTS=<empty> <empty> COLOUR_INTENSITY BLOCK_LIGHTS COLOURED_LIGHTS_RENDER_DISTANCE COLOURED_LIGHTS_RENDER_DISTANCE_VERTICAL MAX_COLOURED_LIGHTS

screen.COLOURED_LIGHTS.columns=2

# Set Sliders (Informa ao jogo quais opções são barras de rolagem)
sliders=SUNLIGHT_I MOONLIGHT_I AMBIENT_I AMBIENT_NIGHT_I SKYLIGHT_I BLOCKLIGHT_I NIGHT_DIM SPECULAR_POWER SPECULAR_INTENSITY shadowMapResolution shadowDistance SHADOW_RANGE SHADOW_RADIUS CAVE_THRESHOLD CAVE_POWER CAVE_STRENGTH NIGHT_CAVE_THRESHOLD NIGHT_CAVE_POWER NIGHT_CAVE_STRENGTH FOG_DENSITY FOG_DENSITY_NIGHT WATER_FOG_DENSITY GOD_RAY_SAMPLES GOD_RAY_INTENSITY MOON_RAY_FACTOR EXPOSURE_DAY EXPOSURE_NIGHT CLOUD_STEPS CLOUD_DENSITY CLOUD_ABSORPTION CLOUD_COVERAGE CLOUD_HEIGHT_MIN CLOUD_HEIGHT_MAX COLOURED_LIGHTS_RENDER_DISTANCE COLOURED_LIGHTS_RENDER_DISTANCE_VERTICAL MAX_COLOURED_LIGHTS COLOUR_INTENSITY

# Forced video settings (Força configurações vanilla)
dynamicHandLight=true
oldHandLight=false
oldLighting=false
separateAo=true
underwaterOverlay=false
vignette=false
