screen = <empty> INFO | <empty> | | <profile> GIMG NOISE BLURCOLOR GLICH #[GIMG] <empty>
screen.columns=3

#profile.Default = NOISE=NOISE
profile.no_glich = NOISE=0.0 GIMG=0.0 GLICH=0.0 BLURCOLOR=0.006
profile.Broke = NOISE=0.3 GIMG=1000 GLICH=1 BLURCOLOR=0.01

sliders = GIMG NOISE BLURCOLOR GLICH