# VISUAL SHADERS v1.0

colortex0Format=RGBA8
colortex1Format=RGBA8
colortex2Format=RG8
colortex3Format=RGB8
colortex4Format=RGB16F
colortex5Format=RGBA8

shadowcolor0Format=RGBA8

colortex1Clear=false
colortex4Clear=false

shadowMapResolution=2048
shadowDistance=80.0
sunPathRotation=-40.0

clouds=off

#define QUALITY 2 // [1 2 3]

#define SATURATION 2.3 // [0.5 0.7 0.9 1.0 1.1 1.3 1.5 1.7 1.9 2.0 2.2 2.5]
#define EXPOSURE 1.15 // [0.5 0.7 0.9 1.0 1.1 1.2 1.3 1.5 1.7 2.0]
#define BRIGHTNESS 1.0 // [0.5 0.7 0.9 1.0 1.1 1.2 1.3 1.5 1.7 2.0]
