iris.features.required=SEPARATE_HARDWARE_SAMPLERS COMPUTE_SHADERS
iris.features.optional=BLOCK_EMISSION_ATTRIBUTE ENTITY_TRANSLUCENT SSBO CUSTOM_IMAGES

image.nImage01 = nSampler01 rgba rgba32f float false false 256 256 256