#if !defined(MATERIAL_IDS_GLSL)
#define MATERIAL_IDS_GLSL
// This file was automatically generated by block_wrangler


#define MATERIAL_WATER 1031
bool materialIsWater(int id) {
	return id == 1031;
}


#define MATERIAL_ICE 1030
bool materialIsIce(int id) {
	return id == 1030;
}


#define MATERIAL_LAVA 1009
bool materialIsLava(int id) {
	return id == 1009;
}


bool materialIsPlant(int id) {
	return id == 1005 || id == 1006 || id == 1007 || id == 1021 || id == 1024 || id == 1026 || id == 1027 || id == 1028 || id == 1029;
}


#define MATERIAL_LEAVES 1024
bool materialIsLeaves(int id) {
	return id == 1024;
}


struct Sway {int value;};
const Sway Sway_NONE = Sway(0);
const Sway Sway_UPPER = Sway(1);
const Sway Sway_LOWER = Sway(2);
const Sway Sway_HANGING = Sway(3);
const Sway Sway_FLOATING = Sway(4);
const Sway Sway_FULL = Sway(5);
Sway materialSwayType(int id) {
	if (id == 1028)
		return Sway_UPPER;
	if (id == 1006 || id == 1027)
		return Sway_LOWER;
	if (id == 1019 || id == 1025 || id == 1026)
		return Sway_HANGING;
	if (id == 1005)
		return Sway_FLOATING;
	if (id == 1024)
		return Sway_FULL;
	return Sway_NONE;
}


#define MATERIAL_TINTED_GLASS 1023
bool materialIsTintedGlass(int id) {
	return id == 1023;
}


#define MATERIAL_GLOW_BERRIES 1022
bool materialIsGlowBerries(int id) {
	return id == 1022;
}


bool materialIsFireLightColor(int id) {
	return id == 1004 || id == 1009 || id == 1011 || id == 1020 || id == 1021;
}


bool materialIsTorchLightColor(int id) {
	return id == 1018 || id == 1019;
}


bool materialIsSoulFireLightColor(int id) {
	return id == 1003 || id == 1017;
}


#define MATERIAL_REDSTONE_LIGHT_COLOR 1016
bool materialIsRedstoneLightColor(int id) {
	return id == 1016;
}


#define MATERIAL_PURPLE_FROGLIGHT 1015
bool materialIsPurpleFroglight(int id) {
	return id == 1015;
}


#define MATERIAL_YELLOW_FROGLIGHT 1014
bool materialIsYellowFroglight(int id) {
	return id == 1014;
}


#define MATERIAL_GREEN_FROGLIGHT 1013
bool materialIsGreenFroglight(int id) {
	return id == 1013;
}


#define MATERIAL_LIGHT_BLOCK 1012
bool materialIsLightBlock(int id) {
	return id == 1012;
}


bool materialIsMetal(int id) {
	return id == 1002 || id == 1010 || id == 1011;
}


bool materialIsMaxEmission(int id) {
	return id == 1008 || id == 1009;
}


bool materialIsLetsLightThrough(int id) {
	return id == 1001 || id == 1002 || id == 1003 || id == 1004 || id == 1005 || id == 1006 || id == 1007;
}


#endif // MATERIAL_IDS_GLSL