sliders=BLUR_SAMPLES BLUR_STRENGTH ENABLE_NOISE

screen=BLUR_SAMPLES BLUR_STRENGTH ENABLE_NOISE <profile>

# Iris-compatible profiles
profile.PVP=BLUR_SAMPLES:4 BLUR_STRENGTH:0.2 ENABLE_NOISE:false
profile.POTATO=BLUR_SAMPLES:12 BLUR_STRENGTH:0.6 ENABLE_NOISE:false
profile.NORMAL=BLUR_SAMPLES:16 BLUR_STRENGTH:1.0 ENABLE_NOISE:true
profile.GHOST=BLUR_SAMPLES:32 BLUR_STRENGTH:2.5 ENABLE_NOISE:true
