name=ESSENTIALS Shader

description=A lightweight Minecraft shader with only essential VFX to simulate realism, even on integrated GPUs.

version=1.0

profile=LOW
screen = <empty> ABOUT_ESSENTIALS <empty>
screen.columns = 3