// Copyright (c) 2026 skotah. All rights reserved. //

vignette=false
clouds=off
sky=off

customTexture.cloudTex = textures/clouds.png

// SCREEN SPACE RAYS //
size.buffer.colortex6=0.25 0.25

// BLOOM RESOLUTIONS 3 PASSES X-Y BLURS //
size.buffer.colortex7=0.2 0.2
size.buffer.colortex8=0.2 0.2
size.buffer.colortex9=0.07 0.07
size.buffer.colortex10=0.07 0.07
size.buffer.colortex11=0.02 0.02
size.buffer.colortex12=0.02 0.02

sliders=SHADOW_RESOLUTION SHADOW_DISTANCE SHADOW_QUALITY SSR_DISTANCE SSR_SAMPLES RAY_SAMPLES RAY_STRENGTH BLOOM_INTENSITY EXPOSURE PORTAL_LAYERS PORTAL_SAMPLES

screen = <profile> [SHADOWS] [POSTPROCESSING] [REFLECTIONS] [RAYS] [MISC]
screen.SHADOWS = SHADOW_RESOLUTION SHADOW_QUALITY SHADOW_DISTANCE
screen.POSTPROCESSING = BLOOM_INTENSITY EXPOSURE
screen.REFLECTIONS = SSR_DISTANCE SSR_SAMPLES
screen.RAYS = RAY_SAMPLES RAY_STRENGTH
screen.MISC = PORTAL_LAYERS PORTAL_SAMPLES

profile.LOW = SHADOW_DISTANCE:100 SHADOW_RESOLUTION:512 SHADOW_QUALITY:9 SSR_DISTANCE:4.0 SSR_SAMPLES:4 RAY_SAMPLES:8 PORTAL_LAYERS:5 PORTAL_SAMPLES:3 !program.overworld/composite10 !program.overworld/composite11 !program.overworld/composite12 !program.overworld/composite13 !program.overworld/composite14 !program.overworld/composite15 !program.nether/composite10 !program.nether/composite11 !program.nether/composite12 !program.nether/composite13 !program.nether/composite14 !program.nether/composite15 !program.end/composite10 !program.end/composite11 !program.end/composite12 !program.end/composite13 !program.end/composite14 !program.end/composite15
profile.MEDIUM = SHADOW_DISTANCE:150 SHADOW_RESOLUTION:1024 SHADOW_QUALITY:9 SSR_DISTANCE:2.0 SSR_SAMPLES:16 RAY_SAMPLES:16 PORTAL_LAYERS:10 PORTAL_SAMPLES:5
profile.HIGH = SHADOW_DISTANCE:300 SHADOW_RESOLUTION:4096 SHADOW_QUALITY:25 SSR_DISTANCE:0.5 SSR_SAMPLES:256 RAY_SAMPLES:64 PORTAL_LAYERS:10 PORTAL_SAMPLES:15