//! Generated by build.zig. Do not edit.
const main = @import("main");
const impl = @import("irisbridge");
pub const enabled = true;
pub fn updateSize(width: u31, height: u31) void {return impl.updateSize(width, height);}
pub fn beginFrame(deltaTime: f32, playerPos: main.vec.Vec3d) void {return impl.beginFrame(deltaTime, playerPos);}
pub fn runPostChain(worldFramebuffer: c_uint, screenWidth: u31, screenHeight: u31) void {return impl.runPostChain(worldFramebuffer, screenWidth, screenHeight);}
pub fn runPreparePasses(screenWidth: u31, screenHeight: u31) void {return impl.runPreparePasses(screenWidth, screenHeight);}
pub fn isActive() bool {return impl.isActive();}
pub fn beginTerrain() bool {return impl.beginTerrain();}
pub fn endTerrain() void {return impl.endTerrain();}
pub fn beginTranslucent() bool {return impl.beginTranslucent();}
pub fn endTranslucent() void {return impl.endTranslucent();}
pub fn beginCubyzShadedDraws() void {return impl.beginCubyzShadedDraws();}
pub fn endCubyzShadedDraws() void {return impl.endCubyzShadedDraws();}
pub fn restoreSceneDepth() void {return impl.restoreSceneDepth();}
pub fn renderShadowMap(chunkLists: *const main.renderer.chunk_meshing.ChunkLists, ambient: main.vec.Vec3f, playerPos: main.vec.Vec3d) void {return impl.renderShadowMap(chunkLists, ambient, playerPos);}
pub fn listShaderPacks(allocator: main.heap.NeverFailingAllocator, out: *main.ListManaged([]const u8)) void {return impl.listShaderPacks(allocator, out);}
pub fn listPackOptions(allocator: main.heap.NeverFailingAllocator, out: *main.ListManaged(main.renderer.ShaderPackOption)) void {return impl.listPackOptions(allocator, out);}
pub fn setPackOption(name: []const u8, value: []const u8) void {return impl.setPackOption(name, value);}
