# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# No need for OIT in the shadow pass, as we currently do not even sample the
# actual color of translucent shadows.
oit.shadow=false

# Enable OIT for the gbuffers pass with a single coefficient buffer of rank 3.
#
# The image format needs to have an alpha channel, so the normal R11F_G11F_B10F
# format we use does not work.
oit.gbuffers=true
oit.gbuffers.coefficientRanks=3
oit.gbuffers.colortex0=0
oit.gbuffers.colortex0.format=RGBA16F
