screen=[INFO] [WavingSettings] [ShadowSettings] [PostProcessing] [EffectsSettings]

# Sliders
sliders=Saturation Exposure Brightness Red Green Blue WavingLeavesSpeed WavingPlantsSpeed ShadowSamples ChromaticAberrationQuality BloomQuality VignetteIntensity

# Toggles
options=Lensflare:0,1,CloudToggle:0,1,FoliageWave:0,1,CinematicBars:0,1,RainPuddles:0,1,ToneMapPreset:0,1,2
values.Lensflare=OFF ON
values.CloudToggle=OFF ON
values.FoliageWave=OFF ON
values.CinematicBars=OFF ON
values.RainPuddles=OFF ON
values.ToneMapPreset=Uncharted2 Reinhard ACES

# Columns
screen.columns=1

# INFO Section
screen.INFO=ShaderTra

# Waving Settings
screen.WavingSettings=[WavingPlants] [WavingLeaves] [WavingWater]
screen.WavingSettings.columns=1
screen.WavingPlants=WavingPlants WavingPlantsSpeed
screen.WavingLeaves=WavingLeaves WavingLeavesSpeed
screen.WavingWater=WaterWave UnderWaterCaustics

# Shadow Settings
screen.ShadowSettings=ShadowMapping ShadowSamples

# Post-Processing Settings
screen.PostProcessing=[WorldColor] Brightness Saturation Exposure Bloom BloomQuality ChromaticAberration ChromaticAberrationQuality Lensflare CinematicBars
screen.WorldColor=Red Green Blue

# Effects Settings
screen.EffectsSettings=VignetteIntensity ToneMapPreset RainPuddles
