screen=Saturation Exposure Brightness Red Green Blue CinematicBars Lensflare CloudToggle

# Sliders
sliders=Saturation Exposure Brightness Red Green Blue

# Toggles
options=CinematicBars:0,1,Lensflare:0,1,CloudToggle:0,1
values.CinematicBars=OFF ON
values.Lensflare=OFF ON
values.CloudToggle=OFF ON

screen.columns=1
